# Generated by Django 6.0.3 on 2026-07-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('productos', '0018_producto_es_paquete_paquetecomponente'),
        ('ventas', '0015_comprobantearca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('contacto_telefono', models.CharField(max_length=40, verbose_name='WhatsApp / teléfono')),
                ('notas', models.TextField(blank=True, verbose_name='Notas del cliente')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('vendido', 'Convertido a venta'), ('descartado', 'Descartado')], default='pendiente', max_length=15)),
                ('leido', models.BooleanField(default=False, help_text='Se marca solo al abrir la campanita de notificaciones — no requiere acción manual.')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('venta', models.ForeignKey(blank=True, help_text='Borrador de venta creado al tocar "Vender". Null hasta ese momento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_origen', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Pedido del catálogo',
                'verbose_name_plural': 'Pedidos del catálogo',
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='productos.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogo.pedido')),
            ],
            options={
                'verbose_name': 'Ítem de pedido',
                'verbose_name_plural': 'Ítems de pedido',
                'ordering': ['id'],
            },
        ),
    ]
