# Generated by Django 6.0.3 on 2026-07-24 18:06

import catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_pedido_descuento_global_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantilla', models.CharField(choices=[('almacen', 'Almacén')], default='almacen', max_length=20, verbose_name='Plantilla activa')),
                ('hero_titulo', models.CharField(blank=True, help_text='Vacío = usa el nombre comercial de la empresa.', max_length=200, verbose_name='Título principal')),
                ('hero_subtitulo', models.TextField(blank=True, help_text='Vacío = usa un texto genérico.', verbose_name='Bajada / subtítulo')),
                ('hero_imagen', models.ImageField(blank=True, help_text='Opcional — si no se carga, el hero se muestra sin foto.', null=True, upload_to=catalogo.models._catalogo_hero_path, verbose_name='Imagen del hero')),
                ('sobre_nosotros', models.TextField(blank=True, verbose_name='Sobre nosotros')),
                ('contacto_texto', models.TextField(blank=True, help_text='Se muestra junto a los datos de contacto en el pie de página.', verbose_name='Texto de contacto')),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del catálogo',
                'verbose_name_plural': 'Configuración del catálogo',
            },
        ),
    ]
