# Generated by Django 6.0.3 on 2026-07-25 03:42

import catalogo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_configuracioncatalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncatalogo',
            name='plantilla',
            field=models.CharField(choices=[('almacen', 'Almacén'), ('bento', 'Bento')], default='almacen', max_length=20, verbose_name='Plantilla activa'),
        ),
        migrations.CreateModel(
            name='SlideHeroCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=catalogo.models._catalogo_slide_path, verbose_name='Imagen')),
                ('eyebrow', models.CharField(blank=True, max_length=60, verbose_name='Texto pequeño (arriba del título)')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cta_texto', models.CharField(default='Ver catálogo completo', max_length=60, verbose_name='Texto del botón')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='catalogo.configuracioncatalogo')),
            ],
            options={
                'verbose_name': 'Slide del hero (catálogo)',
                'verbose_name_plural': 'Slides del hero (catálogo)',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
