# Generated by Django 6.0.3 on 2026-07-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_configuracioncatalogo_plantilla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='color_marca',
            field=models.CharField(blank=True, help_text='Código hex, ej: #e8663d. Vacío = color por defecto.', max_length=7, verbose_name='Color de marca'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='nav_catalogo_label',
            field=models.CharField(blank=True, max_length=30, verbose_name='Texto del menú "Catálogo"'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='nav_combos_label',
            field=models.CharField(blank=True, max_length=30, verbose_name='Texto del menú "Combos"'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='nav_ofertas_label',
            field=models.CharField(blank=True, max_length=30, verbose_name='Texto del menú "Ofertas"'),
        ),
    ]
