# Generated by Django 6.0.3 on 2026-07-28 02:51

import catalogo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_configuracioncatalogo_color_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='destacado1_texto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Texto'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='destacado1_titulo',
            field=models.CharField(blank=True, max_length=80, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='destacado2_texto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Texto'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='destacado2_titulo',
            field=models.CharField(blank=True, max_length=80, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='destacado3_texto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Texto'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='destacado3_titulo',
            field=models.CharField(blank=True, max_length=80, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='horarios_texto',
            field=models.TextField(blank=True, help_text='Texto libre, ej: "Lun a Vie 9 a 18 hs · Sáb 9 a 13 hs".', verbose_name='Horarios de atención'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='institucional_bajada',
            field=models.TextField(blank=True, help_text='Vacío = usa un texto genérico.', verbose_name='Bajada de portada'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='institucional_imagen',
            field=models.ImageField(blank=True, help_text='Opcional — si no se carga, la portada se muestra sin foto.', null=True, upload_to=catalogo.models._catalogo_institucional_path, verbose_name='Imagen de portada'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='institucional_titulo',
            field=models.CharField(blank=True, help_text='Vacío = usa un título genérico.', max_length=200, verbose_name='Título de portada'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='nav_tienda_label',
            field=models.CharField(blank=True, max_length=30, verbose_name='Texto del menú "La tienda"'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='tiktok_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='TikTok'),
        ),
        migrations.CreateModel(
            name='ImagenInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=catalogo.models._catalogo_galeria_path, verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título (opcional)')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='catalogo.configuracioncatalogo')),
            ],
            options={
                'verbose_name': 'Imagen de la galería institucional',
                'verbose_name_plural': 'Imágenes de la galería institucional',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
