# Generated by Django 6.0.3 on 2026-07-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_configuracioncatalogo_destacado1_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='anuncio_texto',
            field=models.CharField(blank=True, help_text='Vacío = usa un texto genérico. Se muestra en una franja fina arriba de todo.', max_length=200, verbose_name='Anuncio (franja superior)'),
        ),
    ]
