# Generated by Django 6.0.3 on 2026-07-28 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_configuracioncatalogo_anuncio_texto'),
        ('productos', '0020_producto_precio_incluye_iva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncatalogo',
            name='anuncio_texto',
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='color_marca_secundario',
            field=models.CharField(blank=True, help_text='Código hex, ej: #111e2f. Vacío = color por defecto. Encabezado, hero y pie de página.', max_length=7, verbose_name='Color secundario'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='hero_producto',
            field=models.ForeignKey(blank=True, help_text='Vacío = se elige automáticamente (el destacado más reciente).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='productos.producto', verbose_name='Producto destacado en el hero'),
        ),
        migrations.AlterField(
            model_name='configuracioncatalogo',
            name='color_marca',
            field=models.CharField(blank=True, help_text='Código hex, ej: #ff9343. Vacío = color por defecto. Botones, precios y detalles.', max_length=7, verbose_name='Color de marca'),
        ),
    ]
