# Generated by Django 6.0.3 on 2026-08-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_remove_configuracioncatalogo_anuncio_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncatalogo',
            name='plantilla',
            field=models.CharField(choices=[('almacen', 'Almacén'), ('bento', 'Bento'), ('kinetic', 'Kinetic')], default='almacen', max_length=20, verbose_name='Plantilla activa'),
        ),
    ]
