# Generated by Django 6.0.3 on 2026-08-02 03:47

import catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_alter_configuracioncatalogo_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='kinetic_hero_fondo',
            field=models.ImageField(blank=True, help_text='Opcional, exclusiva de "Kinetic" — si no se carga, el hero se ve sin fondo, igual que ahora. Se muestra oscurecida y difuminada detrás del texto.', null=True, upload_to=catalogo.models._catalogo_kinetic_hero_fondo_path, verbose_name='Imagen de fondo del hero (Kinetic)'),
        ),
    ]
