# Generated by Django 6.0.3 on 2026-08-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_configuracioncatalogo_kinetic_hero_fondo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncatalogo',
            name='plantilla',
            field=models.CharField(choices=[('almacen', 'Almacén'), ('bento', 'Bento'), ('kinetic', 'Kinetic'), ('lumina', 'Lumina')], default='almacen', max_length=20, verbose_name='Plantilla activa'),
        ),
    ]
