# Generated by Django 6.0.3 on 2026-08-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_alter_configuracioncatalogo_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='color_marca_bento',
            field=models.CharField(blank=True, help_text='Código hex. Vacío = color por defecto de Bento.', max_length=7, verbose_name='Color de marca (Bento)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='color_marca_lumina',
            field=models.CharField(blank=True, help_text='Código hex. Vacío = color por defecto de Lumina.', max_length=7, verbose_name='Color de marca (Lumina)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='color_marca_secundario_bento',
            field=models.CharField(blank=True, help_text='Código hex. Vacío = color por defecto de Bento.', max_length=7, verbose_name='Color secundario (Bento)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='color_marca_secundario_lumina',
            field=models.CharField(blank=True, help_text='Código hex. Vacío = color por defecto de Lumina.', max_length=7, verbose_name='Color secundario (Lumina)'),
        ),
        migrations.AlterField(
            model_name='configuracioncatalogo',
            name='color_marca',
            field=models.CharField(blank=True, help_text='Código hex, ej: #ff9343. Vacío = color por defecto. Botones, precios y detalles.', max_length=7, verbose_name='Color de marca (Almacén)'),
        ),
        migrations.AlterField(
            model_name='configuracioncatalogo',
            name='color_marca_secundario',
            field=models.CharField(blank=True, help_text='Código hex, ej: #111e2f. Vacío = color por defecto. Encabezado, hero y pie de página.', max_length=7, verbose_name='Color secundario (Almacén)'),
        ),
    ]
