# Generated by Django 6.0.3 on 2026-08-10 01:24

import catalogo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_configuracioncatalogo_color_marca_bento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('debajo_hero', 'Debajo del hero (ancho completo)'), ('antes_grilla', 'Arriba de la grilla de productos')], default='debajo_hero', max_length=20, verbose_name='Ubicación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=catalogo.models._catalogo_banner_path, verbose_name='Imagen (opcional)')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('texto', models.CharField(blank=True, max_length=200, verbose_name='Bajada (opcional)')),
                ('color_fondo', models.CharField(blank=True, help_text='Código hex. Vacío = usa el color secundario de la marca. Solo se ve si el banner no tiene imagen.', max_length=7, verbose_name='Color de fondo')),
                ('cta_texto', models.CharField(blank=True, max_length=40, verbose_name='Texto del botón (opcional)')),
                ('cta_url', models.CharField(blank=True, help_text='Sin texto Y link del botón cargados los dos, el banner no muestra botón.', max_length=300, verbose_name='Link del botón (opcional)')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='catalogo.configuracioncatalogo')),
            ],
            options={
                'verbose_name': 'Banner promocional (catálogo)',
                'verbose_name_plural': 'Banners promocionales (catálogo)',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
