# Generated by Django 6.0.3 on 2026-08-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_bannercatalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='color_fondo_bento',
            field=models.CharField(blank=True, help_text='Código hex. Vacío = color por defecto de Bento.', max_length=7, verbose_name='Color de fondo — modo claro (Bento)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='color_fondo_bento_oscuro',
            field=models.CharField(blank=True, help_text='Código hex. Vacío = color por defecto de Bento.', max_length=7, verbose_name='Color de fondo — modo oscuro (Bento)'),
        ),
    ]
