# Generated by Django 6.0.3 on 2026-08-10 03:40

import catalogo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_configuracioncatalogo_color_fondo_bento_and_more'),
        ('productos', '0023_tipoproducto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='hero_spot1_imagen',
            field=models.ImageField(blank=True, help_text='Opcional — con imagen cargada, reemplaza al producto destacado de arriba en esta tarjeta.', null=True, upload_to=catalogo.models._catalogo_bento_hero_spot1_path, verbose_name='Imagen — tarjeta 1 del hero (Bento)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='hero_spot2_imagen',
            field=models.ImageField(blank=True, help_text='Opcional — con imagen cargada, reemplaza al producto de esta tarjeta.', null=True, upload_to=catalogo.models._catalogo_bento_hero_spot2_path, verbose_name='Imagen — tarjeta 2 del hero (Bento)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='hero_spot2_producto',
            field=models.ForeignKey(blank=True, help_text='Vacío = se elige automáticamente (combo destacado, o el siguiente producto destacado).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='productos.producto', verbose_name='Producto — tarjeta 2 del hero (Bento)'),
        ),
    ]
