# Generated by Django 6.0.3 on 2026-08-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_configuracioncatalogo_hero_spot1_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercatalogo',
            name='posicion',
            field=models.CharField(choices=[('debajo_hero', 'Debajo del hero (ancho completo)'), ('antes_grilla', 'Arriba de la grilla de productos'), ('antes_destacados', 'Antes de Destacados'), ('antes_combos', 'Antes de Combos armados')], default='debajo_hero', max_length=20, verbose_name='Ubicación'),
        ),
    ]
