# Generated by Django 6.0.3 on 2026-08-10 17:45

import catalogo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_alter_bannercatalogo_posicion'),
        ('productos', '0023_tipoproducto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='hero_imagen_sin_fondo',
            field=models.BooleanField(default=False, help_text='Si la foto del hero (subida arriba, o la del producto destacado) ya tiene el fondo transparente recortado, activá esto para que flote sin la tarjeta rectangular detrás.', verbose_name='Hero sin tarjeta de fondo (Almacén)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='tiles_destacados_titulo',
            field=models.CharField(blank=True, help_text='Vacío = usa "Categorías y marcas".', max_length=100, verbose_name='Título de la fila de categorías/marcas (Almacén)'),
        ),
        migrations.CreateModel(
            name='TileDestacadoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('categoria', 'Categoría'), ('marca', 'Marca')], default='categoria', max_length=10, verbose_name='Tipo')),
                ('marca', models.CharField(blank=True, help_text='Usada si el tipo es "Marca".', max_length=100, verbose_name='Marca')),
                ('etiqueta', models.CharField(blank=True, help_text='Vacío = usa el nombre de la categoría o el valor de la marca tal cual.', max_length=60, verbose_name='Etiqueta (opcional)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=catalogo.models._catalogo_tile_path, verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, help_text='Usada si el tipo es "Categoría".', null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoriaproducto', verbose_name='Categoría')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles_destacados', to='catalogo.configuracioncatalogo')),
            ],
            options={
                'verbose_name': 'Categoría/marca destacada (catálogo)',
                'verbose_name_plural': 'Categorías/marcas destacadas (catálogo)',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
