# Generated by Django 6.0.3 on 2026-08-14 02:30

import catalogo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_configuracioncatalogo_hero_imagen_sin_fondo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='cta_final_boton_texto',
            field=models.CharField(blank=True, max_length=40, verbose_name='Texto del botón — banda final (Bento)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='cta_final_boton_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='Link del botón — banda final (Bento)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='cta_final_texto',
            field=models.CharField(blank=True, max_length=250, verbose_name='Bajada — banda final (Bento)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='cta_final_titulo',
            field=models.CharField(blank=True, help_text='Opcional — con título cargado aparece una banda de cierre al final de la home, para un mensaje distinto al de "Nuestra historia" (ej. envíos, empresas). Vacío = no se muestra.', max_length=150, verbose_name='Título — banda final (Bento)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='mostrar_historia_en_home',
            field=models.BooleanField(default=True, help_text='El texto de arriba siempre se muestra en La Tienda. Desactivá esto si no querés repetirlo también en la portada del catálogo.', verbose_name='"Nuestra historia" también en la home (Bento)'),
        ),
        migrations.CreateModel(
            name='MarcaLogoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre de la marca')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=catalogo.models._catalogo_marca_logo_path, verbose_name='Logo')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_logo', to='catalogo.configuracioncatalogo')),
            ],
            options={
                'verbose_name': 'Marca (catálogo)',
                'verbose_name_plural': 'Marcas (catálogo)',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TickerMensajeCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=120, verbose_name='Mensaje')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_mensajes', to='catalogo.configuracioncatalogo')),
            ],
            options={
                'verbose_name': 'Mensaje de la barra de anuncios (catálogo)',
                'verbose_name_plural': 'Mensajes de la barra de anuncios (catálogo)',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
