# Generated by Django 6.0.3 on 2026-08-14 18:28

import catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0019_configuracioncatalogo_cta_final_boton_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='cta_final_imagen',
            field=models.ImageField(blank=True, help_text='Opcional — sin imagen, la banda se ve con el color de fondo liso de siempre.', null=True, upload_to=catalogo.models._catalogo_cta_final_path, verbose_name='Imagen de fondo — banda final (Bento)'),
        ),
    ]
