# Generated by Django 6.0.3 on 2026-08-14 18:45

import catalogo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0020_configuracioncatalogo_cta_final_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerBentoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('novedades', 'Novedades (rail de tarjetas, arriba)'), ('promos_mes', 'Promos del mes (grilla fija de 4)'), ('antes_destacados', 'Antes de Destacados (franja ancha)'), ('antes_combos', 'Antes de Combos armados (franja ancha)')], default='novedades', max_length=20, verbose_name='Dónde va')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=catalogo.models._catalogo_banner_bento_path, verbose_name='Imagen (opcional)')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('texto', models.CharField(blank=True, max_length=200, verbose_name='Bajada (opcional)')),
                ('color_fondo', models.CharField(blank=True, help_text='Código hex. Vacío = usa el color secundario de la marca. Solo se ve si el banner no tiene imagen.', max_length=7, verbose_name='Color de fondo')),
                ('cta_texto', models.CharField(blank=True, max_length=40, verbose_name='Texto del botón (opcional)')),
                ('cta_url', models.CharField(blank=True, help_text='Sin texto Y link del botón cargados los dos, el banner no muestra botón.', max_length=300, verbose_name='Link del botón (opcional)')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners_bento', to='catalogo.configuracioncatalogo')),
            ],
            options={
                'verbose_name': 'Banner promocional (Bento)',
                'verbose_name_plural': 'Banners promocionales (Bento)',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
