# Generated by Django 6.0.3 on 2026-08-14 21:03

import catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0021_configuracioncatalogo_tiles_destacados_titulo_bento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='color_fondo_kinetic',
            field=models.CharField(blank=True, help_text='Código hex. Vacío = negro por defecto de Kinetic.', max_length=7, verbose_name='Color de fondo (Kinetic)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='kinetic_banner_cta_texto',
            field=models.CharField(blank=True, max_length=40, verbose_name='Texto del botón — banner destacado (Kinetic)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='kinetic_banner_cta_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='Link del botón — banner destacado (Kinetic)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='kinetic_banner_imagen',
            field=models.ImageField(blank=True, help_text='Opcional — con imagen cargada, aparece un banner grande debajo del hero.', null=True, upload_to=catalogo.models._catalogo_kinetic_banner_path, verbose_name='Imagen — banner destacado (Kinetic)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='kinetic_banner_texto',
            field=models.CharField(blank=True, max_length=240, verbose_name='Texto — banner destacado (Kinetic)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='kinetic_banner_titulo',
            field=models.CharField(blank=True, max_length=120, verbose_name='Título — banner destacado (Kinetic)'),
        ),
    ]
