# Generated by Django 6.0.3 on 2026-08-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0022_configuracioncatalogo_color_fondo_kinetic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='color_marca_kinetic',
            field=models.CharField(blank=True, help_text='Código hex. Vacío = color por defecto de Kinetic.', max_length=7, verbose_name='Color de marca (Kinetic)'),
        ),
    ]
