# Generated by Django 6.0.3 on 2026-08-15 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0023_configuracioncatalogo_color_marca_kinetic'),
        ('productos', '0023_tipoproducto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='combinacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='productos.combinacionvariante'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='combinacion_descripcion',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
