# Generated by Django 6.0.3 on 2026-08-15 00:58

import catalogo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0024_itempedido_combinacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerKineticCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=catalogo.models._catalogo_banner_kinetic_path, verbose_name='Imagen (opcional)')),
                ('titulo', models.CharField(blank=True, max_length=120, verbose_name='Título')),
                ('texto', models.CharField(blank=True, max_length=240, verbose_name='Texto (opcional)')),
                ('cta_texto', models.CharField(blank=True, max_length=40, verbose_name='Texto del botón (opcional)')),
                ('cta_url', models.CharField(blank=True, help_text='Sin texto Y link del botón cargados los dos, el banner no muestra botón.', max_length=300, verbose_name='Link del botón (opcional)')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners_kinetic', to='catalogo.configuracioncatalogo')),
            ],
            options={
                'verbose_name': 'Banner (Kinetic)',
                'verbose_name_plural': 'Banners (Kinetic)',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TickerMensajeKineticCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=80, verbose_name='Mensaje')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_mensajes_kinetic', to='catalogo.configuracioncatalogo')),
            ],
            options={
                'verbose_name': 'Mensaje de la barra de estado (Kinetic)',
                'verbose_name_plural': 'Mensajes de la barra de estado (Kinetic)',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
