# Generated by Django 6.0.3 on 2026-08-15 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0026_migrar_banner_kinetic_unico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncatalogo',
            name='kinetic_banner_cta_texto',
        ),
        migrations.RemoveField(
            model_name='configuracioncatalogo',
            name='kinetic_banner_cta_url',
        ),
        migrations.RemoveField(
            model_name='configuracioncatalogo',
            name='kinetic_banner_imagen',
        ),
        migrations.RemoveField(
            model_name='configuracioncatalogo',
            name='kinetic_banner_texto',
        ),
        migrations.RemoveField(
            model_name='configuracioncatalogo',
            name='kinetic_banner_titulo',
        ),
    ]
