# Generated by Django 6.0.3 on 2026-08-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0027_remove_configuracioncatalogo_kinetic_banner_cta_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerkineticcatalogo',
            name='color_fondo',
            field=models.CharField(blank=True, help_text='Código hex. Vacío = usa el fondo oscuro estándar de Kinetic. Solo se ve si el banner no tiene imagen.', max_length=7, verbose_name='Color de fondo'),
        ),
    ]
