# Generated by Django 6.0.3 on 2026-08-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0028_bannerkinetic_color_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='kinetic_hero_stat1_titulo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Etiqueta 1 (tarjeta hero, Kinetic)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='kinetic_hero_stat1_valor',
            field=models.CharField(blank=True, max_length=40, verbose_name='Valor 1 (tarjeta hero, Kinetic)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='kinetic_hero_stat2_titulo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Etiqueta 2 (tarjeta hero, Kinetic)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='kinetic_hero_stat2_valor',
            field=models.CharField(blank=True, max_length=40, verbose_name='Valor 2 (tarjeta hero, Kinetic)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='kinetic_hero_stat3_titulo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Etiqueta 3 (tarjeta hero, Kinetic)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='kinetic_hero_stat3_valor',
            field=models.CharField(blank=True, max_length=40, verbose_name='Valor 3 (tarjeta hero, Kinetic)'),
        ),
    ]
