# Generated by Django 6.0.3 on 2026-08-15 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0029_kinetic_hero_stats'),
        ('productos', '0023_tipoproducto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='GondolaAlmacenCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Vacío = usa el nombre de la categoría.', max_length=80, verbose_name='Título (opcional)')),
                ('subtitulo', models.CharField(blank=True, max_length=140, verbose_name='Bajada (opcional)')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gondolas_catalogo_almacen', to='productos.categoriaproducto', verbose_name='Categoría')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gondolas_almacen', to='catalogo.configuracioncatalogo')),
            ],
            options={
                'verbose_name': 'Góndola destacada (Almacén)',
                'verbose_name_plural': 'Góndolas destacadas (Almacén)',
                'ordering': ['orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('configuracion', 'categoria'), name='catalogo_gondola_almacen_categoria_unica')],
            },
        ),
    ]
