# Generated by Django 6.0.3 on 2026-08-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0031_alter_configuracioncatalogo_plantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncatalogo',
            name='plantilla',
            field=models.CharField(choices=[('almacen', 'Almacén'), ('bento', 'Bento'), ('kinetic', 'Kinetic'), ('lumina', 'Directo'), ('editorial', 'Editorial')], default='almacen', max_length=20, verbose_name='Plantilla activa'),
        ),
    ]
