# Generated by Django 6.0.3 on 2026-08-16 00:02

import catalogo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0033_kinetic_bitacora_consultas'),
        ('productos', '0023_tipoproducto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='directo_hero_imagen1',
            field=models.ImageField(blank=True, help_text='Opcional — con imagen cargada, reemplaza al producto de esta pieza.', null=True, upload_to=catalogo.models._catalogo_directo_hero_pieza1_path, verbose_name='Imagen — pieza 1 del hero (Directo)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='directo_hero_imagen2',
            field=models.ImageField(blank=True, help_text='Opcional — con imagen cargada, reemplaza al producto de esta pieza.', null=True, upload_to=catalogo.models._catalogo_directo_hero_pieza2_path, verbose_name='Imagen — pieza 2 del hero (Directo)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='directo_hero_imagen3',
            field=models.ImageField(blank=True, help_text='Opcional — con imagen cargada, reemplaza al producto de esta pieza.', null=True, upload_to=catalogo.models._catalogo_directo_hero_pieza3_path, verbose_name='Imagen — pieza 3 del hero (Directo)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='directo_hero_producto1',
            field=models.ForeignKey(blank=True, help_text='Vacío = usa el primer producto destacado automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='productos.producto', verbose_name='Producto — pieza 1 del hero (Directo)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='directo_hero_producto2',
            field=models.ForeignKey(blank=True, help_text='Vacío = usa el segundo producto destacado automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='productos.producto', verbose_name='Producto — pieza 2 del hero (Directo)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='directo_hero_producto3',
            field=models.ForeignKey(blank=True, help_text='Vacío = usa el tercer producto destacado automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='productos.producto', verbose_name='Producto — pieza 3 del hero (Directo)'),
        ),
    ]
