# Generated by Django 6.0.3 on 2026-08-16 00:44

import catalogo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0034_configuracioncatalogo_directo_hero_imagen1_and_more'),
        ('productos', '0023_tipoproducto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='color_marca_editorial',
            field=models.CharField(blank=True, help_text='Código hex. Vacío = rojo editorial por defecto.', max_length=7, verbose_name='Color principal (Editorial)'),
        ),
        migrations.AddField(
            model_name='configuracioncatalogo',
            name='color_marca_secundario_editorial',
            field=models.CharField(blank=True, help_text='Código hex. Vacío = negro editorial por defecto.', max_length=7, verbose_name='Color de tinta (Editorial)'),
        ),
        migrations.CreateModel(
            name='SeleccionEditorialCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('categoria', 'Categoría'), ('producto', 'Producto')], default='categoria', max_length=12, verbose_name='Contenido')),
                ('etiqueta', models.CharField(blank=True, max_length=32, verbose_name='Etiqueta (opcional)')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título (opcional)')),
                ('texto', models.CharField(blank=True, max_length=240, verbose_name='Bajada (opcional)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=catalogo.models._catalogo_coleccion_editorial_path, verbose_name='Portada (opcional)')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selecciones_catalogo_editorial', to='productos.categoriaproducto')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones_editorial', to='catalogo.configuracioncatalogo')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selecciones_catalogo_editorial', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Selección de la edición (Editorial)',
                'verbose_name_plural': 'Selecciones de la edición (Editorial)',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
