# Generated by Django 6.0.3 on 2026-09-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0037_drop_orphan_col_tiles_destacados_titulo_bento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
    ]
