# Generated by Django 6.0.3 on 2026-09-29 18:11

import django.db.models.deletion
from django.db import migrations, models


def corregir_pedidos_vendidos_sin_venta_confirmada(apps, schema_editor):
    """
    Antes, tocar "Vender" marcaba el pedido como VENDIDO en el acto. Los
    que quedaron así con la venta todavía en borrador, o con la venta
    anulada después, en realidad nunca se vendieron: vuelven a PENDIENTE.
    Los que no tienen venta (se borró el borrador) no se tocan: no hay
    forma de saber si se llegaron a vender.
    """
    Pedido = apps.get_model('catalogo', 'Pedido')
    Pedido.objects.filter(
        estado='vendido', venta__estado__in=['borrador', 'anulada'],
    ).update(estado='pendiente')


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0038_alter_itempedido_precio_unitario'),
        ('ventas', '0028_alter_consumoloteventa_costo_unitario_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='venta',
            field=models.ForeignKey(blank=True, help_text='Venta creada al tocar "Vender". El pedido pasa a VENDIDO recién cuando se confirma.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_origen', to='ventas.venta'),
        ),
        migrations.RunPython(corregir_pedidos_vendidos_sin_venta_confirmada, migrations.RunPython.noop),
    ]
