# Generated by Django 6.0.3 on 2026-05-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopermisooverride',
            name='permiso',
            field=models.CharField(choices=[('ver_usuarios', 'Ver lista de usuarios'), ('crear_usuarios', 'Crear usuarios'), ('editar_usuarios', 'Editar usuarios'), ('eliminar_usuarios', 'Eliminar usuarios'), ('gestionar_permisos', 'Gestionar permisos de otros usuarios'), ('ver_clientes', 'Ver lista de clientes'), ('crear_clientes', 'Crear clientes'), ('editar_clientes', 'Editar clientes'), ('eliminar_clientes', 'Eliminar clientes'), ('ver_proveedores', 'Ver lista de proveedores'), ('crear_proveedores', 'Crear proveedores'), ('editar_proveedores', 'Editar proveedores'), ('eliminar_proveedores', 'Eliminar proveedores'), ('ver_stock', 'Ver niveles de stock'), ('ajustar_stock', 'Realizar ajustes de stock'), ('ver_productos', 'Ver lista de productos'), ('crear_productos', 'Crear productos'), ('editar_productos', 'Editar productos'), ('eliminar_productos', 'Eliminar productos'), ('gestionar_categorias', 'Gestionar categorías y tipos de producto'), ('ver_compras', 'Ver historial de compras'), ('crear_compras', 'Crear nuevas compras'), ('editar_compras', 'Editar compras existentes'), ('eliminar_compras', 'Eliminar compras')], max_length=50),
        ),
    ]
