# Generated by Django 6.0.3 on 2026-06-22 02:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuariopermisooverride_permiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(default='Mi Empresa', max_length=200)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('cuit', models.CharField(blank=True, help_text='XX-XXXXXXXX-X', max_length=13)),
                ('condicion_iva', models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('M', 'Monotributista'), ('E', 'Exento'), ('CF', 'Consumidor Final')], max_length=3)),
                ('domicilio', models.CharField(blank=True, max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.models._empresa_logo_path)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Datos de la empresa',
                'verbose_name_plural': 'Datos de la empresa',
            },
        ),
        migrations.AlterField(
            model_name='usuariopermisooverride',
            name='permiso',
            field=models.CharField(choices=[('ver_usuarios', 'Ver lista de usuarios'), ('crear_usuarios', 'Crear usuarios'), ('editar_usuarios', 'Editar usuarios'), ('eliminar_usuarios', 'Eliminar usuarios'), ('gestionar_permisos', 'Gestionar permisos de otros usuarios'), ('editar_empresa', 'Editar datos de la empresa'), ('ver_clientes', 'Ver lista de clientes'), ('crear_clientes', 'Crear clientes'), ('editar_clientes', 'Editar clientes'), ('eliminar_clientes', 'Eliminar clientes'), ('ver_proveedores', 'Ver lista de proveedores'), ('crear_proveedores', 'Crear proveedores'), ('editar_proveedores', 'Editar proveedores'), ('eliminar_proveedores', 'Eliminar proveedores'), ('ver_stock', 'Ver niveles de stock'), ('ajustar_stock', 'Realizar ajustes de stock'), ('ver_productos', 'Ver lista de productos'), ('crear_productos', 'Crear productos'), ('editar_productos', 'Editar productos'), ('eliminar_productos', 'Eliminar productos'), ('gestionar_categorias', 'Gestionar categorías y tipos de producto'), ('ver_compras', 'Ver historial de compras'), ('crear_compras', 'Crear nuevas compras'), ('editar_compras', 'Editar compras existentes'), ('eliminar_compras', 'Eliminar compras'), ('ver_ventas', 'Ver historial de ventas'), ('crear_ventas', 'Crear nuevas ventas'), ('editar_ventas', 'Editar ventas existentes'), ('eliminar_ventas', 'Eliminar ventas'), ('ver_caja', 'Ver balance y movimientos de caja'), ('cargar_movimientos_caja', 'Cargar movimientos manuales en caja'), ('ver_gastos', 'Ver historial de gastos'), ('crear_gastos', 'Crear nuevos gastos'), ('editar_gastos', 'Editar gastos existentes'), ('eliminar_gastos', 'Eliminar gastos')], max_length=50),
        ),
    ]
