# Generated by Django 6.0.3 on 2026-07-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_datosempresa_alter_usuariopermisooverride_permiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Mercado Pago, Naranja X', max_length=100)),
                ('titular', models.CharField(blank=True, max_length=150)),
                ('tipo', models.CharField(choices=[('tarjeta_credito', 'Tarjeta de crédito'), ('tarjeta_debito', 'Tarjeta de débito'), ('billetera_virtual', 'Billetera virtual'), ('cuenta_bancaria', 'Cuenta bancaria')], max_length=20)),
                ('terminada_en', models.CharField(blank=True, help_text='Últimos 4 dígitos, alias o CBU corto. No guardar el número completo de tarjeta.', max_length=20)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dia_cierre', models.PositiveSmallIntegerField(blank=True, help_text='Día del mes en que cierra el resumen (1-31)', null=True)),
                ('dia_vencimiento', models.PositiveSmallIntegerField(blank=True, help_text='Día del mes en que vence el pago (1-31)', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuenta financiera',
                'verbose_name_plural': 'Cuentas financieras',
                'ordering': ['-activa', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='usuariopermisooverride',
            name='permiso',
            field=models.CharField(choices=[('ver_usuarios', 'Ver lista de usuarios'), ('crear_usuarios', 'Crear usuarios'), ('editar_usuarios', 'Editar usuarios'), ('eliminar_usuarios', 'Eliminar usuarios'), ('gestionar_permisos', 'Gestionar permisos de otros usuarios'), ('editar_empresa', 'Editar datos de la empresa'), ('editar_cuentas', 'Cargar y editar cuentas financieras (tarjetas/billeteras)'), ('ver_clientes', 'Ver lista de clientes'), ('crear_clientes', 'Crear clientes'), ('editar_clientes', 'Editar clientes'), ('eliminar_clientes', 'Eliminar clientes'), ('ver_proveedores', 'Ver lista de proveedores'), ('crear_proveedores', 'Crear proveedores'), ('editar_proveedores', 'Editar proveedores'), ('eliminar_proveedores', 'Eliminar proveedores'), ('ver_stock', 'Ver niveles de stock'), ('ajustar_stock', 'Realizar ajustes de stock'), ('ver_productos', 'Ver lista de productos'), ('crear_productos', 'Crear productos'), ('editar_productos', 'Editar productos'), ('eliminar_productos', 'Eliminar productos'), ('gestionar_categorias', 'Gestionar categorías y tipos de producto'), ('ver_compras', 'Ver historial de compras'), ('crear_compras', 'Crear nuevas compras'), ('editar_compras', 'Editar compras existentes'), ('eliminar_compras', 'Eliminar compras'), ('ver_ventas', 'Ver historial de ventas'), ('crear_ventas', 'Crear nuevas ventas'), ('editar_ventas', 'Editar ventas existentes'), ('eliminar_ventas', 'Eliminar ventas'), ('ver_caja', 'Ver balance y movimientos de caja'), ('cargar_movimientos_caja', 'Cargar movimientos manuales en caja'), ('ver_gastos', 'Ver historial de gastos'), ('crear_gastos', 'Crear nuevos gastos'), ('editar_gastos', 'Editar gastos existentes'), ('eliminar_gastos', 'Eliminar gastos')], max_length=50),
        ),
    ]
