# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_cuentafinanciera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopermisooverride',
            name='permiso',
            field=models.CharField(choices=[('ver_usuarios', 'Ver lista de usuarios'), ('crear_usuarios', 'Crear usuarios'), ('editar_usuarios', 'Editar usuarios'), ('eliminar_usuarios', 'Eliminar usuarios'), ('gestionar_permisos', 'Gestionar permisos de otros usuarios'), ('editar_empresa', 'Editar datos de la empresa'), ('editar_cuentas', 'Cargar y editar cuentas de caja (tarjetas, billeteras, bancos)'), ('ver_clientes', 'Ver lista de clientes'), ('crear_clientes', 'Crear clientes'), ('editar_clientes', 'Editar clientes'), ('eliminar_clientes', 'Eliminar clientes'), ('ver_proveedores', 'Ver lista de proveedores'), ('crear_proveedores', 'Crear proveedores'), ('editar_proveedores', 'Editar proveedores'), ('eliminar_proveedores', 'Eliminar proveedores'), ('ver_stock', 'Ver niveles de stock'), ('ajustar_stock', 'Realizar ajustes de stock'), ('ver_productos', 'Ver lista de productos'), ('crear_productos', 'Crear productos'), ('editar_productos', 'Editar productos'), ('eliminar_productos', 'Eliminar productos'), ('gestionar_categorias', 'Gestionar categorías y tipos de producto'), ('ver_compras', 'Ver historial de compras'), ('crear_compras', 'Crear nuevas compras'), ('editar_compras', 'Editar compras existentes'), ('eliminar_compras', 'Eliminar compras'), ('ver_ventas', 'Ver historial de ventas'), ('crear_ventas', 'Crear nuevas ventas'), ('editar_ventas', 'Editar ventas existentes'), ('eliminar_ventas', 'Eliminar ventas'), ('ver_caja', 'Ver balance y movimientos de caja'), ('cargar_movimientos_caja', 'Cargar movimientos manuales en caja'), ('ver_gastos', 'Ver historial de gastos'), ('crear_gastos', 'Crear nuevos gastos'), ('editar_gastos', 'Editar gastos existentes'), ('eliminar_gastos', 'Eliminar gastos')], max_length=50),
        ),
    ]
