# Generated by Django 6.0.3 on 2026-07-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_usuariopermisooverride_permiso_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='titulo',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
