# Generated by Django 6.0.3 on 2026-07-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_usuariopermisooverride_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopermisooverride',
            name='permiso',
            field=models.CharField(choices=[('ver_usuarios', 'Ver lista de usuarios'), ('crear_usuarios', 'Crear usuarios'), ('editar_usuarios', 'Editar usuarios'), ('eliminar_usuarios', 'Eliminar usuarios'), ('gestionar_permisos', 'Gestionar permisos de otros usuarios'), ('editar_empresa', 'Editar datos de la empresa'), ('editar_cuentas', 'Cargar y editar cuentas de caja (tarjetas, billeteras, bancos)'), ('ver_clientes', 'Ver lista de clientes'), ('crear_clientes', 'Crear clientes'), ('editar_clientes', 'Editar clientes'), ('eliminar_clientes', 'Eliminar clientes'), ('ver_proveedores', 'Ver lista de proveedores'), ('crear_proveedores', 'Crear proveedores'), ('editar_proveedores', 'Editar proveedores'), ('eliminar_proveedores', 'Eliminar proveedores'), ('ver_stock', 'Ver niveles de stock'), ('ajustar_stock', 'Realizar ajustes de stock'), ('ver_productos', 'Ver lista de productos'), ('crear_productos', 'Crear productos'), ('editar_productos', 'Editar productos'), ('eliminar_productos', 'Eliminar productos'), ('gestionar_categorias', 'Gestionar categorías y tipos de producto'), ('gestionar_listas_descuento', 'Gestionar listas de descuento'), ('gestionar_ofertas', 'Gestionar ofertas'), ('ver_compras', 'Ver historial de compras'), ('crear_compras', 'Crear nuevas compras'), ('editar_compras', 'Editar compras existentes'), ('eliminar_compras', 'Eliminar compras'), ('ver_ventas', 'Ver historial de ventas'), ('crear_ventas', 'Crear nuevas ventas'), ('editar_ventas', 'Editar ventas existentes'), ('eliminar_ventas', 'Eliminar ventas'), ('ver_balanza', 'Ver etiquetas de balanza generadas'), ('crear_balanza', 'Generar etiquetas de balanza'), ('anular_balanza', 'Anular una etiqueta de balanza antes de venderse'), ('ver_caja', 'Ver balance y movimientos de caja'), ('cargar_movimientos_caja', 'Cargar movimientos manuales en caja'), ('abrir_cerrar_turno', 'Abrir y cerrar turnos de caja diaria'), ('ver_transacciones', 'Ver transacciones entre cuentas'), ('crear_transacciones', 'Crear transacciones entre cuentas'), ('anular_transacciones', 'Anular transacciones'), ('ver_gastos', 'Ver historial de ingresos y egresos'), ('crear_gastos', 'Crear ingresos y egresos'), ('editar_gastos', 'Editar ingresos y egresos existentes'), ('eliminar_gastos', 'Eliminar ingresos y egresos'), ('ver_deudas', 'Ver créditos y préstamos'), ('crear_deudas', 'Crear créditos y préstamos'), ('editar_deudas', 'Editar créditos y préstamos existentes'), ('eliminar_deudas', 'Eliminar créditos y préstamos'), ('confirmar_cuotas_deuda', 'Confirmar el pago de una cuota'), ('ver_cheques', 'Ver cheques'), ('crear_cheques', 'Crear cheques'), ('editar_cheques', 'Editar cheques existentes'), ('eliminar_cheques', 'Eliminar cheques'), ('confirmar_cheques', 'Confirmar o rechazar el cobro/pago de un cheque'), ('ver_notas', 'Ver el anotador'), ('crear_notas', 'Crear notas'), ('editar_notas', 'Editar notas'), ('eliminar_notas', 'Eliminar notas'), ('crear_notas_privadas', 'Marcar notas propias como privadas')], max_length=50),
        ),
    ]
