# Generated by Django 6.0.3 on 2026-07-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_usuariopermisooverride_permiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionArca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False, help_text='Si está apagado, las ventas no intentan pedir CAE aunque haya certificado cargado.', verbose_name='Facturación electrónica habilitada')),
                ('ambiente', models.CharField(choices=[('testing', 'Testing / Homologación'), ('produccion', 'Producción')], default='testing', max_length=12)),
                ('punto_venta', models.PositiveIntegerField(default=1, help_text='Punto de venta habilitado en ARCA como "Web Service / Factura Electrónica".', verbose_name='Punto de venta')),
                ('certificado_pem', models.TextField(blank=True, verbose_name='Certificado (.crt)')),
                ('clave_privada_enc', models.TextField(blank=True, verbose_name='Clave privada (cifrada)')),
                ('wsaa_token', models.TextField(blank=True)),
                ('wsaa_sign', models.TextField(blank=True)),
                ('wsaa_expira', models.DateTimeField(blank=True, null=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración ARCA',
                'verbose_name_plural': 'Configuración ARCA',
            },
        ),
    ]
