# Generated by Django 6.0.3 on 2026-07-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_configuracionarca'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionarca',
            name='csr_generado_el',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionarca',
            name='csr_pendiente',
            field=models.TextField(blank=True),
        ),
    ]
