# Generated by Django 6.0.3 on 2026-07-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_usuariopermisooverride_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cond_iva',
            field=models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('M', 'Monotributista'), ('E', 'Exento'), ('CF', 'Consumidor Final')], help_text='Se usa para decidir si corresponde Factura A, B o C al facturar.', max_length=2, verbose_name='Condición ante IVA'),
        ),
    ]
