# Generated by Django 6.0.3 on 2026-08-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_usuariopermisooverride_permiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosempresa',
            name='eslogan',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
