# Generated by Django 6.0.3 on 2026-08-29 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_datosempresa_eslogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='scoring_actualizado_el',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='scoring_calculado',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='cliente',
            name='scoring_desglose',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='scoring_override',
            field=models.IntegerField(blank=True, help_text='Puntaje fijado a mano. Reemplaza al cálculo automático.', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='scoring_override_el',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='scoring_override_motivo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='cliente',
            name='scoring_override_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorings_ajustados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='scoring_sin_historial',
            field=models.BooleanField(default=True, help_text='El cliente nunca compró en cuotas ni pagó con cheque.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='scoring',
            field=models.IntegerField(default=1000, help_text='Riesgo de pago (0–1000). Lo calcula el sistema; 1000 = sin historial / excelente.'),
        ),
    ]
