# Generated by Django 6.0.3 on 2026-09-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_usuariopermisooverride_permiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitir_venta_sin_stock', models.BooleanField(default=False, help_text='Si está activo, se puede confirmar una venta aunque no haya stock suficiente: el stock queda en negativo y el turno de caja no se puede cerrar hasta cargar la mercadería que falta (una compra o un ajuste de stock). Si está apagado, el sistema rechaza cualquier venta o movimiento que deje stock negativo.', verbose_name='Permitir vender sin stock')),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de ventas',
                'verbose_name_plural': 'Configuración de ventas',
            },
        ),
    ]
