# Generated by Django 6.0.3 on 2026-09-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_configuracionventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorBilletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominaciones', models.JSONField(blank=True, default=list)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contador de billetes',
                'verbose_name_plural': 'Contador de billetes',
            },
        ),
    ]
