# Generated by Django 6.0.3 on 2026-09-04 21:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_contadorbilletes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionLimiteContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, help_text='Si está apagado, no se calcula ni se muestra el resumen de facturación.')),
                ('nombre_categoria', models.CharField(blank=True, help_text='Categoría de monotributo actual, a modo informativo (ej. "Categoría D").', max_length=50)),
                ('limite_anual', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tope de ingresos brutos anuales de la categoría, según ARCA.', max_digits=14)),
                ('incluir_efectivo', models.BooleanField(default=True, help_text='Prendido (recomendado): cuenta todos los medios de pago, que es lo que realmente exige ARCA. Apagado: muestra el acumulado excluyendo efectivo, como vista adicional.')),
                ('umbral_alerta_pct', models.PositiveSmallIntegerField(default=80, help_text='Porcentaje del límite a partir del cual se avisa que se está acercando.')),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de límite contable',
                'verbose_name_plural': 'Configuración de límite contable',
            },
        ),
    ]
