# Generated by Django 6.0.3 on 2026-09-04 22:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_configuracionlimitecontable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_pagare',
            field=models.ImageField(blank=True, help_text='Foto del pagaré en blanco ya firmado, por si se pierde el papel.', null=True, upload_to='clientes/pagares/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_pagare',
            field=models.CharField(blank=True, help_text='N° del pagaré en blanco firmado por el total de sus cuentas, si corresponde.', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionlimitecontable',
            name='limite_mensual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tope de facturación del mes en curso, opcional (0 = no se controla).', max_digits=14),
        ),
        migrations.AddField(
            model_name='configuracionlimitecontable',
            name='solo_facturado_arca',
            field=models.BooleanField(default=False, help_text='Apagado (recomendado): cuenta toda venta confirmada, esté o no facturada electrónicamente (es ingreso bruto igual). Prendido: cuenta solo lo que generó comprobante ARCA (CAE) real, como vista adicional.'),
        ),
        migrations.AlterField(
            model_name='configuracionlimitecontable',
            name='limite_anual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tope de ingresos brutos anuales de la categoría según ARCA, opcional (0 = no se controla).', max_digits=14),
        ),
    ]
