# Generated by Django 6.0.3 on 2026-09-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_usuariopermisooverride_permiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('score', models.IntegerField()),
                ('banda', models.CharField(max_length=20)),
                ('desglose', models.JSONField(default=list)),
                ('es_backfill', models.BooleanField(default=False, help_text='True si este punto lo generó el comando de reconstrucción retroactiva (backfill_historial_scoring) a partir de fechas reales del historial, no un recálculo en el momento.')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_scoring', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Historial de scoring',
                'verbose_name_plural': 'Historial de scoring',
                'ordering': ['fecha'],
                'unique_together': {('cliente', 'fecha')},
            },
        ),
    ]
