# Generated by Django 6.0.3 on 2026-09-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_historialscoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosempresa',
            name='fecha_inicio_actividades',
            field=models.DateField(blank=True, help_text='La misma que figura en tu Constancia de Inscripción de AFIP/ARCA (no la fecha en que empezaste a usar este sistema).', null=True, verbose_name='Fecha de inicio de actividades'),
        ),
        migrations.AddField(
            model_name='datosempresa',
            name='ingresos_brutos',
            field=models.CharField(blank=True, help_text='N° de inscripción en Ingresos Brutos (Rentas de tu provincia). Si sos Monotributista sin inscripción provincial aparte, se suele repetir el mismo CUIT.', max_length=20, verbose_name='Ingresos Brutos'),
        ),
    ]
