# Generated by Django 6.0.3 on 2026-09-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_datosempresa_fecha_inicio_actividades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionventas',
            name='vencidos_baja_automatica',
            field=models.BooleanField(default=True, help_text='Si está activo, un lote vencido se da de baja solo como pérdida por vencimiento, pasados los días de tolerancia. Si está apagado, queda marcado como vencido hasta que se venda o se dé de baja a mano.', verbose_name='Dar de baja los lotes vencidos'),
        ),
        migrations.AddField(
            model_name='configuracionventas',
            name='vencidos_dias_tolerancia',
            field=models.PositiveSmallIntegerField(default=0, help_text='Días después del vencimiento en los que el lote todavía se puede vender (con aviso en el carrito). 0 = se da de baja al día siguiente de vencer.', verbose_name='Días de tolerancia para vencidos'),
        ),
    ]
