# Generated by Django 6.0.3 on 2026-06-12 23:44

import django.db.models.deletion
import ventas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_usuariopermisooverride_permiso'),
        ('productos', '0005_alter_productocolor_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Se genera automáticamente: VTA-00001', max_length=20, unique=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notas', models.TextField(blank=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha', '-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(blank=True, help_text='Snapshot del nombre del producto al momento de la venta.', max_length=255)),
                ('producto_codigo', models.CharField(blank=True, help_text='Snapshot del código del producto al momento de la venta.', max_length=50)),
                ('cliente_nombre', models.CharField(blank=True, help_text='Snapshot del nombre del cliente al momento de la venta.', max_length=200)),
                ('color_nombre', models.CharField(blank=True, help_text='Snapshot del nombre del color al momento de la venta.', max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('moneda', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=5)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('condicion_pago', models.CharField(blank=True, choices=[('contado', 'Contado'), ('15', '15 días'), ('30', '30 días'), ('60', '60 días'), ('90', '90 días'), ('convenir', 'A convenir')], default='contado', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Factura / Nº Referencia')),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_venta', to='core.cliente')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_venta', to='productos.productocolor', verbose_name='Color / variante')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_venta', to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Ítem de venta',
                'verbose_name_plural': 'Ítems de venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VentaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=ventas.models._venta_doc_path)),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('remito', 'Remito'), ('recibo', 'Recibo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('subido_el', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Documento de venta',
                'verbose_name_plural': 'Documentos de venta',
                'ordering': ['subido_el'],
            },
        ),
    ]
