# Generated by Django 6.0.3 on 2026-06-14 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_confirmadas', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
        migrations.AddField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('credito', 'Crédito'), ('qr', 'QR')], default='efectivo', max_length=20, verbose_name='Medio de pago'),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='color_nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='producto_codigo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='producto_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
