# Generated by Django 6.0.3 on 2026-06-28 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_opcionvariante_variante_and_more'),
        ('ventas', '0004_pagoventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemventa',
            name='color',
        ),
        migrations.RemoveField(
            model_name='itemventa',
            name='color_nombre',
        ),
        migrations.AddField(
            model_name='itemventa',
            name='combinacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_venta', to='productos.combinacionvariante', verbose_name='Combinación de variantes'),
        ),
        migrations.AddField(
            model_name='itemventa',
            name='combinacion_descripcion',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
