# Generated by Django 6.0.3 on 2026-07-04 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_itemcompra_fecha_vencimiento_lotecompra'),
        ('ventas', '0005_remove_itemventa_color_remove_itemventa_color_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventa',
            name='lote_escaneado',
            field=models.ForeignKey(blank=True, help_text='Solo se completa si tipo_escaneo=lote_especifico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_venta_escaneados', to='compras.lotecompra', verbose_name='Lote escaneado puntualmente'),
        ),
        migrations.AddField(
            model_name='itemventa',
            name='tipo_escaneo',
            field=models.CharField(choices=[('normal', 'Código normal (último lote disponible)'), ('lote_especifico', 'Código de lote específico')], default='normal', max_length=20),
        ),
        migrations.CreateModel(
            name='ConsumoLoteVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('lote_codigo_snapshot', models.CharField(blank=True, max_length=20)),
                ('costo_unitario_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('item_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='ventas.itemventa')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_venta', to='compras.lotecompra')),
            ],
            options={
                'verbose_name': 'Consumo de lote (venta)',
                'verbose_name_plural': 'Consumos de lote (venta)',
                'ordering': ['id'],
            },
        ),
    ]
