# Generated by Django 6.0.3 on 2026-07-10 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0012_alter_gasto_options_gasto_cuenta_gasto_tipo_and_more'),
        ('ventas', '0006_itemventa_lote_escaneado_itemventa_tipo_escaneo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_venta', to='caja.cuentacaja'),
        ),
    ]
