# Generated by Django 6.0.3 on 2026-07-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_pagoventa_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventa',
            name='lista_descuento_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la lista si el % vino de ahí (ver ListaDescuento); vacío si se escribió el % a mano.', max_length=100, verbose_name='Lista de descuento aplicada'),
        ),
    ]
