# Generated by Django 6.0.3 on 2026-07-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_itemventa_lista_descuento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumoloteventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
