# Generated by Django 6.0.3 on 2026-07-16 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_producto_unidades_por_presentacion_and_more'),
        ('ventas', '0009_alter_consumoloteventa_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaBalanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Se genera automáticamente: BAL-2026-00001', max_length=20, unique=True)),
                ('producto_nombre_snapshot', models.CharField(blank=True, max_length=255)),
                ('unidad_medida_snapshot', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('vendida', 'Vendida'), ('anulada', 'Anulada')], default='disponible', max_length=12)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=300)),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiquetas_balanza_anuladas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiquetas_balanza_creadas', to=settings.AUTH_USER_MODEL)),
                ('item_venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiqueta_balanza_origen', to='ventas.itemventa')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etiquetas_balanza', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Etiqueta de balanza',
                'verbose_name_plural': 'Etiquetas de balanza',
                'ordering': ['-fecha_alta'],
            },
        ),
    ]
