# Generated by Django 6.0.3 on 2026-07-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_etiquetabalanza'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventa',
            name='oferta_aplicada_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la Oferta si el % vino de una promoción vigente (automática o elegida a mano); vacío si no aplica.', max_length=100, verbose_name='Oferta aplicada'),
        ),
    ]
