# Generated by Django 6.0.3 on 2026-07-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_itemventa_oferta_aplicada_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento_global_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento global (%)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='oferta_global_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la Oferta (tipo=umbral) que originó el descuento global, si la hay.', max_length=100, verbose_name='Oferta global aplicada'),
        ),
    ]
