# Generated by Django 6.0.3 on 2026-07-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_venta_descuento_global_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemventa',
            name='descuento_pct',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Descuento (%)'),
        ),
    ]
