# Generated by Django 6.0.3 on 2026-07-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_alter_itemventa_descuento_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='cotizacion',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Pesos por unidad de la moneda de la cuenta. Solo aplica si la cuenta no es en pesos.', max_digits=12, null=True, verbose_name='Cotización'),
        ),
    ]
