# Generated by Django 6.0.3 on 2026-07-20 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_pagoventa_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteArca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.PositiveSmallIntegerField(choices=[(1, 'Factura A'), (6, 'Factura B'), (11, 'Factura C')])),
                ('punto_venta', models.PositiveIntegerField()),
                ('numero', models.PositiveIntegerField()),
                ('cae', models.CharField(max_length=20)),
                ('cae_vencimiento', models.DateField()),
                ('ambiente', models.CharField(choices=[('testing', 'Testing / Homologación'), ('produccion', 'Producción')], max_length=12)),
                ('doc_tipo', models.PositiveSmallIntegerField(help_text='Código AFIP: 80=CUIT, 96=DNI, 99=Consumidor Final, etc.')),
                ('doc_nro', models.CharField(blank=True, max_length=20)),
                ('condicion_iva_receptor_id', models.PositiveSmallIntegerField(help_text='Código de FEParamGetCondicionIvaReceptor (5=Consumidor Final, etc.)')),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('importe_neto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('importe_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('respuesta_json', models.JSONField(blank=True, help_text='Respuesta cruda de ARCA (FECAESolicitar), para auditoría/debug.', null=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante_arca', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Comprobante ARCA',
                'verbose_name_plural': 'Comprobantes ARCA',
            },
        ),
    ]
