# Generated by Django 6.0.3 on 2026-07-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_alter_pagoventa_medio_alter_venta_medio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventa',
            name='alicuota_iva',
            field=models.CharField(blank=True, choices=[('0', 'Exento (0%)'), ('10.5', 'Reducido (10,5%)'), ('21', 'General (21%)'), ('27', 'Especial (27%)')], max_length=5, verbose_name='Alícuota IVA'),
        ),
    ]
