# Generated by Django 6.0.3 on 2026-07-29 01:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0018_alter_movimientocaja_origen_cuentaporcobrar_and_more'),
        ('ventas', '0017_itemventa_alicuota_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='cantidad_pagos',
            field=models.PositiveSmallIntegerField(default=1, help_text='Plan de pagos de la tarjeta de crédito (1, 3, 6...). Siempre 1 para los demás medios.', verbose_name='Cantidad de pagos'),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='recargo_monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto de recargo (en la moneda de `cuenta`), ya incluido en `monto`.', max_digits=14, verbose_name='Recargo'),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='recargo_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Porcentaje de recargo aplicado a esta línea, snapshot de RecargoMedioPago.', max_digits=5, verbose_name='Recargo %'),
        ),
        migrations.CreateModel(
            name='RecargoMedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(choices=[('transferencia', 'Transferencia'), ('debito', 'Débito'), ('credito', 'Crédito'), ('qr', 'QR')], max_length=20)),
                ('cantidad_pagos', models.PositiveSmallIntegerField(default=1, help_text='Solo aplica a Crédito. Para los demás medios siempre es 1.', verbose_name='Cantidad de pagos')),
                ('recargo_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Recargo %')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargos', to='caja.cuentacaja')),
            ],
            options={
                'verbose_name': 'Recargo por medio de pago',
                'verbose_name_plural': 'Recargos por medio de pago',
                'ordering': ['cuenta', 'medio', 'cantidad_pagos'],
                'unique_together': {('cuenta', 'medio', 'cantidad_pagos')},
            },
        ),
    ]
