# Generated by Django 6.0.3 on 2026-07-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_pagoventa_cantidad_pagos_pagoventa_recargo_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recargomediopago',
            name='nombre_plan',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nombre del plan'),
        ),
    ]
