# Generated by Django 6.0.3 on 2026-07-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_recargomediopago_nombre_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='nombre_plan',
            field=models.CharField(blank=True, help_text='Nombre comercial del plan (ej. "Plan Z"), snapshot de RecargoMedioPago.nombre_plan.', max_length=60, verbose_name='Nombre del plan'),
        ),
    ]
