# Generated by Django 6.0.3 on 2026-07-29 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0019_cuentacaja_acepta_credito_cuentacaja_acepta_debito_and_more'),
        ('ventas', '0020_pagoventa_nombre_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('acepta_debito', models.BooleanField(default=True)),
                ('acepta_credito', models.BooleanField(default=True)),
                ('acepta_qr', models.BooleanField(default=True)),
                ('acepta_transferencia', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarjeta/billetera de pago',
                'verbose_name_plural': 'Tarjetas/billeteras de pago',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='recargomediopago',
            options={'ordering': ['tarjeta', 'medio', 'cantidad_pagos'], 'verbose_name': 'Recargo por medio de pago', 'verbose_name_plural': 'Recargos por medio de pago'},
        ),
        migrations.AlterField(
            model_name='recargomediopago',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recargos_viejo', to='caja.cuentacaja'),
        ),
        migrations.AlterUniqueTogether(
            name='recargomediopago',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_venta', to='ventas.tarjetapago'),
        ),
        migrations.AddField(
            model_name='recargomediopago',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recargos', to='ventas.tarjetapago'),
        ),
        migrations.AlterUniqueTogether(
            name='recargomediopago',
            unique_together={('tarjeta', 'medio', 'cantidad_pagos')},
        ),
    ]
