# Generated by Django 6.0.3 on 2026-07-29 04:49
#
# Paso B de la migración a TarjetaPago (ver 0021 y 0023): por cada
# CuentaCaja que tenía recargos cargados (RecargoMedioPago.cuenta), crea
# una TarjetaPago con el mismo nombre y los mismos acepta_*, y reapunta
# esas filas de RecargoMedioPago (y los PagoVenta históricos que las
# usaron) a la tarjeta nueva — no se pierde ningún recargo ya cargado.

from django.db import migrations


def migrar_a_tarjetas(apps, schema_editor):
    CuentaCaja = apps.get_model('caja', 'CuentaCaja')
    TarjetaPago = apps.get_model('ventas', 'TarjetaPago')
    RecargoMedioPago = apps.get_model('ventas', 'RecargoMedioPago')
    PagoVenta = apps.get_model('ventas', 'PagoVenta')

    cuentas_con_recargo = CuentaCaja.objects.filter(
        recargos_viejo__isnull=False,
    ).distinct()

    mapa_cuenta_a_tarjeta = {}
    for cuenta in cuentas_con_recargo:
        tarjeta, _ = TarjetaPago.objects.get_or_create(
            nombre=cuenta.nombre,
            defaults={
                'acepta_debito': cuenta.acepta_debito,
                'acepta_credito': cuenta.acepta_credito,
                'acepta_qr': cuenta.acepta_qr,
                'acepta_transferencia': cuenta.acepta_transferencia,
            },
        )
        mapa_cuenta_a_tarjeta[cuenta.pk] = tarjeta

    for recargo in RecargoMedioPago.objects.filter(cuenta_id__in=mapa_cuenta_a_tarjeta):
        recargo.tarjeta = mapa_cuenta_a_tarjeta[recargo.cuenta_id]
        recargo.save(update_fields=['tarjeta'])

    # Best-effort: los PagoVenta históricos con recargo ya cobrado también
    # quedan enlazados a la tarjeta (por nombre de cuenta), para que el
    # historial muestre "pagado con Mercado Pago" en vez de quedar vacío.
    for pago in PagoVenta.objects.filter(recargo_monto__gt=0, cuenta_id__in=mapa_cuenta_a_tarjeta):
        pago.tarjeta = mapa_cuenta_a_tarjeta[pago.cuenta_id]
        pago.save(update_fields=['tarjeta'])


def revertir(apps, schema_editor):
    RecargoMedioPago = apps.get_model('ventas', 'RecargoMedioPago')
    PagoVenta = apps.get_model('ventas', 'PagoVenta')
    TarjetaPago = apps.get_model('ventas', 'TarjetaPago')

    RecargoMedioPago.objects.update(tarjeta=None)
    PagoVenta.objects.update(tarjeta=None)
    TarjetaPago.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0021_paso_a_agregar_tarjetapago'),
    ]

    operations = [
        migrations.RunPython(migrar_a_tarjetas, revertir),
    ]
