# Generated by Django 6.0.3 on 2026-08-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_paso_c_tarjeta_obligatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoventa',
            name='medio',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('credito', 'Crédito'), ('qr', 'QR'), ('cuotas', 'Cuotas'), ('cheque', 'Cheque')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('credito', 'Crédito'), ('qr', 'QR'), ('cuotas', 'Cuotas'), ('cheque', 'Cheque')], default='efectivo', max_length=20, verbose_name='Medio de pago'),
        ),
    ]
