# Generated by Django 6.0.3 on 2026-08-06 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0030_alter_movimientocaja_origen'),
        ('compras', '0018_compra_numero_comprobante'),
        ('ventas', '0024_alter_pagoventa_medio_alter_venta_medio_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha', models.DateField(help_text='Fecha contable de la devolución.')),
                ('descripcion', models.CharField(help_text='Motivo/descripción cargada a mano.', max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, default=0, help_text='Lo efectivamente reembolsado, en la moneda de "cuenta".', max_digits=14)),
                ('cotizacion', models.DecimalField(blank=True, decimal_places=4, help_text='Pesos por unidad de la moneda de la cuenta. Solo aplica si la cuenta no es en pesos.', max_digits=12, null=True, verbose_name='Cotización')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_venta_creadas', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(blank=True, help_text='De qué cuenta sale el reembolso. Vacío si no se devuelve plata.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_venta', to='caja.cuentacaja')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Devolución de venta',
                'verbose_name_plural': 'Devoluciones de venta',
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionVentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre_snapshot', models.CharField(blank=True, max_length=255)),
                ('combinacion_desc_snapshot', models.CharField(blank=True, max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('es_perdida', models.BooleanField(default=False, help_text='True si la unidad devuelta está rota/no reutilizable — no vuelve al stock vendible, se registra como Perdida en su lugar (ver registrar_perdida en compras.models).')),
                ('motivo_perdida', models.CharField(blank=True, help_text='Choices de compras.models.MotivoPerdida. Solo aplica si es_perdida=True.', max_length=20)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.devolucionventa')),
                ('item_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='ventas.itemventa')),
            ],
            options={
                'verbose_name': 'Ítem de devolución de venta',
                'verbose_name_plural': 'Ítems de devolución de venta',
            },
        ),
        migrations.CreateModel(
            name='DevolucionVentaConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_codigo_snapshot', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fue_perdida', models.BooleanField(default=False)),
                ('consumo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='ventas.consumoloteventa')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_venta', to='compras.lotecompra')),
                ('perdida', models.ForeignKey(blank=True, help_text='La Perdida que registró esta porción, si fue_perdida=True.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucion_origen', to='compras.perdida')),
                ('devolucion_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='ventas.devolucionventaitem')),
            ],
            options={
                'verbose_name': 'Consumo de devolución (venta)',
                'verbose_name_plural': 'Consumos de devolución (venta)',
            },
        ),
    ]
