# Generated by Django 6.0.3 on 2026-09-02 14:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0025_devolucionventa_devolucionventaitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='redondeo_monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Lo que el cliente pagó por encima del precio de los productos (en pesos), ya incluido en `monto`.', max_digits=14, verbose_name='Redondeo a favor'),
        ),
    ]
