# Generated by Django 6.0.3 on 2026-09-17 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0026_pagoventa_redondeo_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantearca',
            name='tipo_comprobante',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Factura A'), (3, 'Nota de Crédito A'), (6, 'Factura B'), (8, 'Nota de Crédito B'), (11, 'Factura C'), (13, 'Nota de Crédito C')]),
        ),
        migrations.CreateModel(
            name='NotaCreditoArca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.PositiveSmallIntegerField(choices=[(1, 'Factura A'), (3, 'Nota de Crédito A'), (6, 'Factura B'), (8, 'Nota de Crédito B'), (11, 'Factura C'), (13, 'Nota de Crédito C')])),
                ('punto_venta', models.PositiveIntegerField()),
                ('numero', models.PositiveIntegerField()),
                ('cae', models.CharField(max_length=20)),
                ('cae_vencimiento', models.DateField()),
                ('ambiente', models.CharField(choices=[('testing', 'Testing / Homologación'), ('produccion', 'Producción')], max_length=12)),
                ('doc_tipo', models.PositiveSmallIntegerField(help_text='Código AFIP: 80=CUIT, 96=DNI, 99=Consumidor Final, etc.')),
                ('doc_nro', models.CharField(blank=True, max_length=20)),
                ('condicion_iva_receptor_id', models.PositiveSmallIntegerField(help_text='Código de FEParamGetCondicionIvaReceptor (5=Consumidor Final, etc.)')),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('importe_neto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('importe_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('respuesta_json', models.JSONField(blank=True, help_text='Respuesta cruda de ARCA (FECAESolicitar), para auditoría/debug.', null=True)),
                ('comprobante_original', models.ForeignKey(help_text='La factura que esta NC corrige (CbteAsoc ante ARCA).', on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='ventas.comprobantearca')),
                ('devolucion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nota_credito_arca', to='ventas.devolucionventa')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito_arca', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Nota de crédito ARCA',
                'verbose_name_plural': 'Notas de crédito ARCA',
            },
        ),
    ]
