# Generated by Django 6.0.3 on 2026-09-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0027_alter_comprobantearca_tipo_comprobante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumoloteventa',
            name='costo_unitario_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='etiquetabalanza',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Precio unitario'),
        ),
    ]
