# Generated by Django 6.0.3 on 2026-08-07 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0029_alter_usuariopermisooverride_permiso'),
        ('productos', '0022_producto_codigo_proveedor_producto_costo_activado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Se genera automáticamente: PRE-00001', max_length=20, unique=True)),
                ('fecha', models.DateField(help_text='Fecha de emisión del presupuesto.')),
                ('cliente_nombre', models.CharField(blank=True, help_text='Snapshot del nombre del cliente elegido, o un nombre libre si todavía no está registrado como Cliente (ej. un posible revendedor nuevo que solo está averiguando precios).', max_length=200, verbose_name='Cliente')),
                ('notas', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='core.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='ItemPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(blank=True, max_length=255)),
                ('combinacion_descripcion', models.CharField(blank=True, max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('descuento_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Descuento (%)')),
                ('lista_descuento_nombre', models.CharField(blank=True, max_length=100, verbose_name='Lista de descuento aplicada')),
                ('stock_al_emitir', models.DecimalField(blank=True, decimal_places=3, help_text='Stock disponible visto al momento de armar el presupuesto (solo informativo — no se reserva ni se descuenta nada).', max_digits=12, null=True)),
                ('combinacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_presupuesto', to='productos.combinacionvariante')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_presupuesto', to='productos.producto')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='presupuestos.presupuesto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
