# Generated by Django 6.0.3 on 2026-09-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempresupuesto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Precio unitario'),
        ),
    ]
