# Generated by Django 6.0.3 on 2026-07-18 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reporte_periodico', 'Reporte periódico'), ('alerta_vencimiento', 'Producto por vencer'), ('alerta_deuda', 'Deuda próxima a vencer'), ('deuda_pagada', 'Deuda pagada'), ('stock_estancado', 'Stock sin movimiento')], max_length=30)),
                ('referencia', models.CharField(blank=True, help_text='Identificador del objeto referido (código de lote, id de cuota, etc).', max_length=50)),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=255)),
                ('canal', models.CharField(default='email', max_length=10)),
                ('exito', models.BooleanField(default=True)),
                ('detalle_error', models.TextField(blank=True)),
                ('enviado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación enviada',
                'verbose_name_plural': 'Historial de notificaciones',
                'ordering': ['-enviado_el'],
                'indexes': [models.Index(fields=['tipo', 'referencia', 'enviado_el'], name='asistencia__tipo_5c0dca_idx')],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.EmailField(blank=True, help_text='Si se deja vacío, se usa el email del usuario.', max_length=254)),
                ('recibir_email', models.BooleanField(default=True)),
                ('recibir_whatsapp', models.BooleanField(default=False)),
                ('frecuencia_reporte', models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual')], default='mensual', max_length=10)),
                ('dia_mes_reporte', models.PositiveSmallIntegerField(default=1, help_text='Día del mes (1-28) en que se manda el reporte mensual.')),
                ('dia_semana_reporte', models.PositiveSmallIntegerField(default=0, help_text='Día de la semana del reporte semanal (0=lunes ... 6=domingo).')),
                ('dias_aviso_vencimiento', models.PositiveSmallIntegerField(default=14, help_text='Avisar productos que vencen dentro de esta cantidad de días.')),
                ('dias_aviso_deuda', models.PositiveSmallIntegerField(default=2, help_text='Avisar deudas que vencen dentro de esta cantidad de días.')),
                ('dias_stock_estancado', models.PositiveSmallIntegerField(default=60, help_text='Sin ventas en esta cantidad de días = stock estancado.')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_reporte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de reporte',
                'verbose_name_plural': 'Preferencias de reporte',
            },
        ),
    ]
