# Generated by Django 6.0.3 on 2026-07-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialnotificacion',
            name='tipo',
            field=models.CharField(choices=[('reporte_periodico', 'Reporte periódico'), ('alerta_vencimiento', 'Producto por vencer'), ('alerta_deuda', 'Deuda próxima a vencer'), ('deuda_pagada', 'Deuda pagada'), ('stock_estancado', 'Stock sin movimiento'), ('alerta_cheque', 'Cheque próximo a vencer')], max_length=30),
        ),
    ]
