# Generated by Django 6.0.3 on 2026-07-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_historialnotificacion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Solo email'), ('whatsapp', 'Solo WhatsApp'), ('ambos', 'Email y WhatsApp'), ('ninguno', 'Ninguno (desactivado)')], default='email', max_length=10)),
                ('email_destino', models.EmailField(blank=True, help_text='Si se deja vacío, se usa el email de Datos de la empresa.', max_length=254)),
                ('whatsapp_destino', models.CharField(blank=True, help_text='Número con código de país (ej: 5491122334455). Todavía no implementado.', max_length=30)),
                ('recibir_reporte_mensual', models.BooleanField(default=True)),
                ('dia_mes_reporte', models.PositiveSmallIntegerField(default=1, help_text='Día del mes (1-28) en que se manda el reporte mensual.')),
                ('recibir_reporte_semanal', models.BooleanField(default=False)),
                ('dia_semana_reporte', models.PositiveSmallIntegerField(default=0, help_text='Día de la semana del reporte semanal (0=lunes ... 6=domingo).')),
                ('recibir_alerta_vencimiento', models.BooleanField(default=True)),
                ('dias_aviso_vencimiento', models.PositiveSmallIntegerField(default=14, help_text='Avisar productos que vencen dentro de esta cantidad de días.')),
                ('recibir_alerta_deuda', models.BooleanField(default=True)),
                ('dias_aviso_deuda', models.PositiveSmallIntegerField(default=2, help_text='Avisar deudas que vencen dentro de esta cantidad de días.')),
                ('recibir_deuda_pagada', models.BooleanField(default=True)),
                ('recibir_stock_estancado', models.BooleanField(default=True)),
                ('dias_stock_estancado', models.PositiveSmallIntegerField(default=60, help_text='Sin ventas en esta cantidad de días = stock estancado.')),
                ('recibir_alerta_cheques', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preferencia de asistencia',
                'verbose_name_plural': 'Preferencia de asistencia',
            },
        ),
        migrations.DeleteModel(
            name='PreferenciaReporte',
        ),
    ]
