# Generated by Django 6.0.3 on 2026-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_preferenciaasistencia_delete_preferenciareporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciaasistencia',
            name='recibir_cuota_cobro_confirmada',
            field=models.BooleanField(default=True, help_text='Avisar cuando un cliente paga una cuota de una venta financiada en cuotas.'),
        ),
        migrations.AlterField(
            model_name='historialnotificacion',
            name='tipo',
            field=models.CharField(choices=[('reporte_periodico', 'Reporte periódico'), ('alerta_vencimiento', 'Producto por vencer'), ('alerta_deuda', 'Deuda próxima a vencer'), ('deuda_pagada', 'Deuda pagada'), ('cuota_cobro_confirmada', 'Cobro de cuota confirmado'), ('stock_estancado', 'Stock sin movimiento'), ('alerta_cheque', 'Cheque próximo a vencer')], max_length=30),
        ),
    ]
