# Generated by Django 6.0.3 on 2026-04-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cuit', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional'), ('monotributo', 'Monotributista'), ('otro', 'Otro')], default='nacional', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('sitio_web', models.URLField(blank=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción interna del proveedor')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('contacto_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre del contacto')),
                ('contacto_cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo del contacto')),
                ('calle', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, default='Argentina', max_length=100)),
                ('condicion_pago', models.CharField(choices=[('contado', 'Contado'), ('15', '15 días'), ('30', '30 días'), ('60', '60 días'), ('90', '90 días'), ('convenir', 'A convenir')], default='contado', max_length=20)),
                ('moneda', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=5)),
                ('dias_entrega', models.PositiveSmallIntegerField(blank=True, help_text='Días hábiles promedio de entrega', null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas internas / condiciones especiales')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
