# Generated by Django 6.0.3 on 2026-05-01 15:46

import django.db.models.deletion
import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de producto',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de producto',
                'verbose_name_plural': 'Tipos de producto',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Se genera automáticamente (PRD-00001).', max_length=50, unique=True)),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('codigo_barras', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_corto', models.CharField(blank=True, help_text='Para tickets y etiquetas.', max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('descripcion_publica', models.TextField(blank=True, help_text='Para catálogo público / e-commerce.')),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=150)),
                ('pais_origen', models.CharField(blank=True, max_length=100, verbose_name='País de origen')),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('gr', 'Gramo'), ('lt', 'Litro'), ('ml', 'Mililitro'), ('mt', 'Metro'), ('cm', 'Centímetro'), ('mt2', 'Metro cuadrado'), ('mt3', 'Metro cúbico'), ('caja', 'Caja'), ('pack', 'Pack / Set'), ('par', 'Par'), ('docena', 'Docena'), ('rollo', 'Rollo'), ('bolsa', 'Bolsa'), ('otro', 'Otro')], default='unidad', max_length=20)),
                ('contenido_neto', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('alto_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Alto (cm)')),
                ('ancho_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ancho (cm)')),
                ('profundidad_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Profundidad (cm)')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de venta')),
                ('precio_mayorista', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio mayorista')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio oferta')),
                ('alicuota_iva', models.CharField(choices=[('0', 'Exento (0%)'), ('10.5', 'Reducido (10,5%)'), ('21', 'General (21%)'), ('27', 'Especial (27%)')], default='21', max_length=5, verbose_name='Alícuota IVA')),
                ('precio_incluye_iva', models.BooleanField(default=True, verbose_name='Precio incluye IVA')),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock mínimo')),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Stock máximo')),
                ('permite_stock_negativo', models.BooleanField(default=False)),
                ('gestiona_stock', models.BooleanField(default=True, verbose_name='Gestiona stock')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('discontinuado', 'Discontinuado'), ('agotado', 'Agotado (sin reposición)')], default='activo', max_length=20)),
                ('publicado', models.BooleanField(default=False, help_text='Visible en catálogo público.')),
                ('destacado', models.BooleanField(default=False)),
                ('requiere_refrigeracion', models.BooleanField(default=False, verbose_name='Requiere refrigeración')),
                ('es_fragil', models.BooleanField(default=False, verbose_name='Es frágil')),
                ('es_peligroso', models.BooleanField(default=False, verbose_name='Es peligroso / Hazmat')),
                ('posicion_deposito', models.CharField(blank=True, max_length=50, verbose_name='Posición en depósito')),
                ('notas', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por coma.', max_length=500)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoriaproducto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.proveedor', verbose_name='Proveedor principal')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.tipoproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=productos.models._producto_imagen_path)),
                ('es_portada', models.BooleanField(default=False)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('subida_el', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['-es_portada', 'orden', 'subida_el'],
            },
        ),
    ]
