# Generated by Django 6.0.3 on 2026-05-03 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoriaproducto_tipoproducto_producto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra a proveedor'), ('ajuste_pos', 'Ajuste positivo (corrección)'), ('devolucion_v', 'Devolución de venta'), ('transf_e', 'Transferencia (entrada)'), ('inventario_e', 'Inventario inicial'), ('venta', 'Venta'), ('ajuste_neg', 'Ajuste negativo (corrección)'), ('devolucion_c', 'Devolución a proveedor'), ('transf_s', 'Transferencia (salida)'), ('merma', 'Merma / Pérdida'), ('uso_interno', 'Uso interno')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Siempre positivo. El tipo determina si es entrada o salida.', max_digits=12)),
                ('stock_anterior', models.DecimalField(decimal_places=3, help_text='Stock antes del movimiento (se completa automáticamente).', max_digits=12)),
                ('stock_posterior', models.DecimalField(decimal_places=3, help_text='Stock después del movimiento (se completa automáticamente).', max_digits=12)),
                ('motivo', models.CharField(blank=True, help_text='Descripción libre del motivo.', max_length=300)),
                ('referencia', models.CharField(blank=True, help_text='N° de compra, orden, remito, etc.', max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='productos.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-fecha'],
            },
        ),
    ]
