# Generated by Django 6.0.3 on 2026-05-30 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_movimientostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color_unico',
            field=models.CharField(blank=True, help_text='Color del producto (solo cuando no gestiona variantes por color).', max_length=50, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_variantes_color',
            field=models.BooleanField(default=False, help_text='Activar si este producto existe en varios colores con stock independiente. El stock total será la suma del stock de cada color.', verbose_name='Gestiona variantes por color'),
        ),
        migrations.CreateModel(
            name='ProductoColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Rojo, Azul marino, Negro mate.', max_length=50, verbose_name='Nombre del color')),
                ('codigo_hex', models.CharField(blank=True, help_text='Opcional. Formato #RRGGBB. Para mostrar una pastilla de color en la UI.', max_length=7, verbose_name='Color (hex)')),
                ('sku_variante', models.CharField(blank=True, help_text='SKU específico de este color. Si está vacío, se usa el SKU del producto.', max_length=100, verbose_name='SKU variante')),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock actual')),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, help_text='Alerta de stock bajo para este color específico.', max_digits=12, verbose_name='Stock mínimo')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar para preservar trazabilidad.')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualización en formularios y punto de venta.')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Color de producto',
                'verbose_name_plural': 'Colores de producto',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('producto', 'nombre')},
            },
        ),
    ]
