# Generated by Django 6.0.3 on 2026-05-31 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_color_unico_producto_tiene_variantes_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productocolor',
            options={'ordering': ['nombre'], 'verbose_name': 'Color de producto', 'verbose_name_plural': 'Colores de producto'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_incluye_iva',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_mayorista',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_oferta',
        ),
        migrations.RemoveField(
            model_name='productocolor',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='productocolor',
            name='stock_minimo',
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Color afectado. Null si el producto no tiene variantes de color.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='productos.productocolor'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='cantidad',
            field=models.PositiveIntegerField(help_text='Siempre positivo. El tipo determina si es entrada o salida.'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='referencia',
            field=models.CharField(blank=True, help_text='N° de compra, venta, remito, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='stock_anterior',
            field=models.PositiveIntegerField(help_text='Stock total del producto antes del movimiento (calculado automáticamente).'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='stock_posterior',
            field=models.PositiveIntegerField(help_text='Stock total del producto después del movimiento (calculado automáticamente).'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color_unico',
            field=models.CharField(blank=True, help_text='Color informativo cuando no se gestionan variantes (ej: "Azul marino").', max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='contenido_neto',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Contenido por unidad (ej: 500 para una botella de 500 ml).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Producto destacado en catálogo.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='gestiona_stock',
            field=models.BooleanField(default=True, help_text='Desactivar para productos de tipo servicio o sin control de inventario.', verbose_name='Gestiona stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas internas del equipo.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='permite_stock_negativo',
            field=models.BooleanField(default=False, help_text='Permite registrar ventas aunque no haya stock disponible.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='posicion_deposito',
            field=models.CharField(blank=True, help_text='Ej: A3-P2. Ubicación física en el depósito.', max_length=50, verbose_name='Posición en depósito'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio final de venta al público (IVA incluido).', max_digits=12, null=True, verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Visible en catálogo público / e-commerce.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_maximo',
            field=models.PositiveIntegerField(blank=True, help_text='Límite sugerido de stock. Orientativo para compras.', null=True, verbose_name='Stock máximo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, help_text='Alerta de stock bajo cuando el total cae por debajo de este valor.', verbose_name='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tags',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por coma (ej: importado, liquidación).', max_length=500),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tiene_variantes_color',
            field=models.BooleanField(default=False, help_text='Activar si el producto existe en varios colores con stock independiente.', verbose_name='Gestiona variantes por color'),
        ),
        migrations.AlterField(
            model_name='productocolor',
            name='codigo_hex',
            field=models.CharField(blank=True, help_text='Opcional. Formato #RRGGBB.', max_length=7, verbose_name='Color (hex)'),
        ),
        migrations.AlterField(
            model_name='productocolor',
            name='sku_variante',
            field=models.CharField(blank=True, help_text='SKU específico de este color. Si está vacío se usa el SKU del producto.', max_length=100, verbose_name='SKU variante'),
        ),
        migrations.AlterField(
            model_name='productocolor',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock actual'),
        ),
    ]
