# Generated by Django 6.0.3 on 2026-06-28 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_productocolor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Opción de variante',
                'verbose_name_plural': 'Opciones de variantes',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='productocolor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productocolor',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='color',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='color_unico',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tiene_variantes_color',
        ),
        migrations.AddField(
            model_name='producto',
            name='es_perecedero',
            field=models.BooleanField(default=False, help_text='Producto con fecha de vencimiento.', verbose_name='Es perecedero'),
        ),
        migrations.AddField(
            model_name='producto',
            name='gestiona_variantes',
            field=models.BooleanField(default=False, help_text='Activar si el producto tiene variantes (color, sabor, talle, aroma, etc.) con stock independiente.', verbose_name='Gestiona variantes'),
        ),
        migrations.CreateModel(
            name='CombinacionVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras específico para esta combinación.', max_length=100, verbose_name='Código de barras')),
                ('sku_variante', models.CharField(blank=True, help_text='SKU específico de esta combinación. Si está vacío se usa el SKU del producto.', max_length=100, verbose_name='SKU variante')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Stock actual')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar para preservar trazabilidad.')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Combinación de variante',
                'verbose_name_plural': 'Combinaciones de variantes',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='combinacion',
            field=models.ForeignKey(blank=True, help_text='Combinación afectada. Null si el producto no tiene variantes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='productos.combinacionvariante'),
        ),
        migrations.CreateModel(
            name='CombinacionVarianteOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combinacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='productos.combinacionvariante')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.opcionvariante')),
            ],
            options={
                'verbose_name': 'Opción de combinación',
                'verbose_name_plural': 'Opciones de combinación',
            },
        ),
        migrations.AddField(
            model_name='opcionvariante',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='productos.variante'),
        ),
    ]
