# Generated by Django 6.0.3 on 2026-06-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_itemcompra_combinacion_and_more'),
        ('productos', '0006_opcionvariante_variante_and_more'),
        ('ventas', '0005_remove_itemventa_color_remove_itemventa_color_nombre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoColor',
        ),
        migrations.AlterUniqueTogether(
            name='combinacionvarianteopcion',
            unique_together={('combinacion', 'opcion')},
        ),
        migrations.AlterUniqueTogether(
            name='opcionvariante',
            unique_together={('variante', 'nombre')},
        ),
    ]
