# Generated by Django 6.0.3 on 2026-06-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_add_descripcion_combinacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinacionvariante',
            name='descripcion_combinacion',
            field=models.CharField(blank=True, help_text='Generada automáticamente a partir de las opciones seleccionadas.', max_length=200, verbose_name='Descripción de combinación'),
        ),
    ]
