# Generated by Django 6.0.3 on 2026-07-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_combinacionvariante_descripcion_combinacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Ej: 10 = 10% de descuento.', max_digits=5, verbose_name='Porcentaje')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lista de descuento',
                'verbose_name_plural': 'Listas de descuento',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
