# Generated by Django 6.0.3 on 2026-07-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_listadescuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_actual',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Costo del lote activo más reciente. Se recalcula solo desde compras — nunca se edita a mano.', max_digits=12, null=True, verbose_name='Costo actual'),
        ),
        migrations.AddField(
            model_name='producto',
            name='modo_precio',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático (costo + % ganancia)')], default='manual', max_length=10, verbose_name='Modo de precio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_ganancia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo si modo_precio=automático. Ej: 35 → precio = costo × 1.35.', max_digits=6, null=True, verbose_name='% de ganancia'),
        ),
    ]
