# Generated by Django 6.0.3 on 2026-07-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_producto_costo_actual_producto_modo_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinacionvariante',
            name='stock_actual',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock actual'),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, help_text='Siempre positivo. El tipo determina si es entrada o salida.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='stock_anterior',
            field=models.DecimalField(decimal_places=3, help_text='Stock total del producto antes del movimiento (calculado automáticamente).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='stock_posterior',
            field=models.DecimalField(decimal_places=3, help_text='Stock total del producto después del movimiento (calculado automáticamente).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_maximo',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Límite sugerido de stock. Orientativo para compras.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Alerta de stock bajo cuando el total cae por debajo de este valor.', max_digits=12),
        ),
    ]
