# Generated by Django 6.0.3 on 2026-07-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_combinacionvariante_stock_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra a proveedor'), ('ajuste_pos', 'Ajuste positivo (corrección)'), ('devolucion_v', 'Devolución de venta'), ('transf_e', 'Transferencia (entrada)'), ('inventario_e', 'Inventario inicial'), ('fracc_e', 'Fraccionamiento (paquete armado)'), ('venta', 'Venta'), ('ajuste_neg', 'Ajuste negativo (corrección)'), ('devolucion_c', 'Devolución a proveedor'), ('transf_s', 'Transferencia (salida)'), ('merma', 'Merma / Pérdida'), ('uso_interno', 'Uso interno'), ('fracc_s', 'Fraccionamiento (consumido a granel)')], max_length=20),
        ),
    ]
