# Generated by Django 6.0.3 on 2026-07-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_alter_movimientostock_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidades_por_presentacion',
            field=models.PositiveIntegerField(blank=True, help_text='Cuántas piezas individuales trae cada "unidad de medida" (ej: una Caja de vasos trae 10 vasos → 10). Dejar vacío si no aplica.', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='contenido_neto',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Cuánto pesa/mide cada pieza individual (o la presentación entera si no trae piezas sueltas). Solo informativo, ej: 500 para una botella de 500 ml.', max_digits=10, null=True),
        ),
    ]
