# Generated by Django 6.0.3 on 2026-07-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_producto_unidades_por_presentacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Ej: 50 = 50% de descuento.', max_digits=5, verbose_name='Porcentaje')),
                ('fecha_inicio', models.DateField(verbose_name='Vigencia desde')),
                ('fecha_fin', models.DateField(verbose_name='Vigencia hasta')),
                ('dias_semana', models.CharField(blank=True, help_text='Días permitidos separados por coma (0=lunes ... 6=domingo). Vacío = todos los días de la semana (ej: "5,6" = solo fin de semana).', max_length=20)),
                ('aplicacion', models.CharField(choices=[('automatica', 'Automática (se aplica sola en el carrito)'), ('manual', 'Manual (el vendedor la elige)')], default='automatica', max_length=12, verbose_name='Aplicación')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='ofertas', to='productos.categoriaproducto', verbose_name='Categorías alcanzadas')),
                ('productos', models.ManyToManyField(blank=True, related_name='ofertas', to='productos.producto', verbose_name='Productos alcanzados')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['-fecha_inicio', 'orden', 'nombre'],
            },
        ),
    ]
