# Generated by Django 6.0.3 on 2026-07-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='cantidad_lleva',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cuántas unidades hacen falta para que aplique el grupo (ej: 3 en un 3x2).', null=True, verbose_name='Llevá'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='cantidad_paga',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cuántas de esas unidades se pagan (ej: 2 en un 3x2). Debe ser menor a "Llevá".', null=True, verbose_name='Pagá'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo',
            field=models.CharField(choices=[('porcentaje', 'Descuento %'), ('nxm', 'Llevá X, pagá Y (2x1, 3x2...)')], default='porcentaje', max_length=12, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 50 = 50% de descuento. Obligatorio si el tipo es Descuento %.', max_digits=5, null=True, verbose_name='Porcentaje'),
        ),
    ]
