# Generated by Django 6.0.3 on 2026-07-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_oferta_cantidad_lleva_oferta_cantidad_paga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='base_calculo',
            field=models.CharField(blank=True, choices=[('bruto', 'Precio de lista (antes de otros descuentos)'), ('neto', 'Total ya con descuentos de línea aplicados')], default='neto', help_text='Sobre qué monto se mide el mínimo — a elección de cada oferta.', max_length=10, verbose_name='Base de cálculo'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='monto_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de compra a partir del cual aplica el descuento.', max_digits=14, null=True, verbose_name='Monto mínimo'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 50 = 50% de descuento. Obligatorio salvo en tipo NXM.', max_digits=5, null=True, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo',
            field=models.CharField(choices=[('porcentaje', 'Descuento %'), ('nxm', 'Llevá X, pagá Y (2x1, 3x2...)'), ('umbral', 'Descuento por monto mínimo de compra')], default='porcentaje', max_length=12, verbose_name='Tipo'),
        ),
    ]
