# Generated by Django 6.0.3 on 2026-07-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_oferta_base_calculo_oferta_monto_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_paquete',
            field=models.BooleanField(default=False, help_text='Combo armado a partir de otros productos. No tiene stock propio: se calcula de sus componentes.', verbose_name='Es un paquete'),
        ),
        migrations.CreateModel(
            name='PaqueteComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, help_text='Cuántas unidades de este componente lleva cada unidad del paquete.', max_digits=12)),
                ('combinacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usada_en_paquetes', to='productos.combinacionvariante', verbose_name='Combinación (si el componente tiene variantes)')),
                ('paquete', models.ForeignKey(limit_choices_to={'es_paquete': True}, on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='productos.producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_paquetes', to='productos.producto', verbose_name='Producto componente')),
            ],
            options={
                'verbose_name': 'Componente de paquete',
                'verbose_name_plural': 'Componentes de paquete',
                'ordering': ['id'],
                'unique_together': {('paquete', 'producto', 'combinacion')},
            },
        ),
    ]
