# Generated by Django 6.0.3 on 2026-07-26 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_producto_es_paquete_paquetecomponente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Característica de producto',
                'verbose_name_plural': 'Características de producto',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
