# Generated by Django 6.0.3 on 2026-07-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_caracteristicaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_incluye_iva',
            field=models.BooleanField(default=True, help_text='Si lo destildás, cargás el precio SIN IVA (tu ganancia real) y el sistema calcula solo el precio final sumándole el IVA.', verbose_name='El precio ya incluye IVA'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio final de venta al público (siempre con IVA ya sumado, ver precio_incluye_iva para cómo se llega a este número).', max_digits=12, null=True, verbose_name='Precio de venta'),
        ),
    ]
