# Generated by Django 6.0.3 on 2026-08-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_producto_precio_incluye_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo cargado a mano — para productos migrados cuyo stock ya se pagó antes de usar este sistema (no hay Compra real que lo respalde). Alimenta el precio automático y el costo de venta SOLO hasta que el producto tenga su primera Compra real: a partir de ahí, el costo pasa a tomarse de la compra.', max_digits=12, null=True, verbose_name='Costo de referencia'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_actual',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Costo real del último lote de una Compra, o -si el producto todavía no tiene ninguna- el costo de referencia cargado a mano (ver "costo"). Nunca se edita a mano directamente.', max_digits=12, null=True, verbose_name='Costo actual'),
        ),
    ]
