# Generated by Django 6.0.3 on 2026-08-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_producto_costo_alter_producto_costo_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_proveedor',
            field=models.CharField(blank=True, help_text='El código con el que EL PROVEEDOR identifica este producto en su propia factura/presupuesto — no es un código nuestro. Sirve para buscar el producto exacto cuando llega un presupuesto de costos actualizados.', max_length=100, verbose_name='Código del proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_activado_en',
            field=models.DateTimeField(blank=True, editable=False, help_text='Cuándo se activó por última vez `costo` como el costo vigente a mano (ver Producto.activar_costo_referencia()). Se compara contra la fecha del último lote real para decidir cuál de los dos costos es más reciente.', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo cargado a mano. Sirve para productos migrados cuyo stock ya se pagó antes de usar este sistema (no hay Compra real que lo respalde) — mientras el producto no tenga ninguna Compra, alimenta el precio automático y el costo de venta solo. También sirve para avisar una reposición más cara sin haberla comprado todavía (ver "activar_costo_referencia()"): al activarlo, manda por sobre el costo de la última Compra real hasta que llegue una Compra más nueva.', max_digits=12, null=True, verbose_name='Costo de referencia'),
        ),
    ]
