# Generated by Django 6.0.3 on 2026-08-09 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_producto_codigo_proveedor_producto_costo_activado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos', to='productos.categoriaproducto', verbose_name='Categoría'),
        ),
    ]
