# Generated by Django 6.0.3 on 2026-09-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0023_tipoproducto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='permite_stock_negativo',
        ),
    ]
