# Generated by Django 6.0.3 on 2026-09-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_remove_producto_permite_stock_negativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_paquete',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo con modo_precio=automático en un paquete. Se resta sobre la suma de los precios de venta de los componentes. Ej: 10 → 10% más barato que comprar los componentes por separado.', max_digits=6, null=True, verbose_name='% de descuento (paquete automático)'),
        ),
    ]
