# Generated by Django 6.0.3 on 2026-09-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0025_producto_descuento_paquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Costo cargado a mano. Sirve para productos migrados cuyo stock ya se pagó antes de usar este sistema (no hay Compra real que lo respalde) — mientras el producto no tenga ninguna Compra, alimenta el precio automático y el costo de venta solo. También sirve para avisar una reposición más cara sin haberla comprado todavía (ver "activar_costo_referencia()"): al activarlo, manda por sobre el costo de la última Compra real hasta que llegue una Compra más nueva.', max_digits=14, null=True, verbose_name='Costo de referencia'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_actual',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, help_text='Costo real del último lote de una Compra, o -si el producto todavía no tiene ninguna- el costo de referencia cargado a mano (ver "costo"). Nunca se edita a mano directamente.', max_digits=14, null=True, verbose_name='Costo actual'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Precio final de venta al público (siempre con IVA ya sumado, ver precio_incluye_iva para cómo se llega a este número).', max_digits=14, null=True, verbose_name='Precio de venta'),
        ),
    ]
