# Generated by Django 6.0.3 on 2026-09-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0026_alter_producto_costo_alter_producto_costo_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra a proveedor'), ('ajuste_pos', 'Ajuste positivo (corrección)'), ('devolucion_v', 'Devolución de venta'), ('transf_e', 'Transferencia (entrada)'), ('inventario_e', 'Inventario inicial'), ('fracc_e', 'Fraccionamiento (paquete armado)'), ('recupero_perd', 'Recupero de pérdida (vencido vendido)'), ('venta', 'Venta'), ('ajuste_neg', 'Ajuste negativo (corrección)'), ('devolucion_c', 'Devolución a proveedor'), ('transf_s', 'Transferencia (salida)'), ('merma', 'Merma / Pérdida'), ('uso_interno', 'Uso interno'), ('fracc_s', 'Fraccionamiento (consumido a granel)')], max_length=20),
        ),
    ]
