# Generated by Django 6.0.3 on 2026-06-20 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo_default', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='egreso', max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('es_sistema', models.BooleanField(default=False, help_text='Concepto usado internamente por el sistema (Venta/Compra). No editable desde la UI.')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Concepto de movimiento',
                'verbose_name_plural': 'Conceptos de movimiento',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('banco', 'Cuenta bancaria'), ('otra', 'Otra')], default='efectivo', max_length=20)),
                ('moneda', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=5)),
                ('caja', models.CharField(choices=[('grande', 'Caja grande'), ('diaria', 'Caja diaria')], default='grande', help_text='A qué libro pertenece esta cuenta (grande o diaria).', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta de caja',
                'verbose_name_plural': 'Cuentas de caja',
                'ordering': ['caja', 'orden', 'nombre'],
                'unique_together': {('nombre', 'caja')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caja', models.CharField(choices=[('grande', 'Caja grande'), ('diaria', 'Caja diaria')], default='grande', max_length=10)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Siempre positivo. El campo "tipo" determina si suma o resta.', max_digits=14)),
                ('moneda', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=5)),
                ('fecha', models.DateField(help_text='Fecha contable del movimiento (puede diferir de fecha_alta).')),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('referencia', models.CharField(blank=True, help_text='N° de venta, compra, comprobante, etc.', max_length=100)),
                ('origen', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('manual', 'Carga manual'), ('ajuste', 'Ajuste')], default='manual', max_length=10)),
                ('origen_app', models.CharField(blank=True, help_text="App del objeto origen, ej. 'ventas' o 'compras'.", max_length=20)),
                ('origen_id', models.PositiveIntegerField(blank=True, help_text='PK de la Venta/Compra que generó este movimiento.', null=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.conceptomovimiento')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.cuentacaja')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-fecha', '-fecha_alta'],
                'indexes': [models.Index(fields=['origen', 'origen_app', 'origen_id'], name='caja_movimi_origen_5ad917_idx'), models.Index(fields=['caja', 'fecha'], name='caja_movimi_caja_b314b4_idx')],
            },
        ),
    ]
