# Generated by Django 6.0.3 on 2026-06-21 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Hora del gasto (automática)'),
        ),
    ]
