# Generated by Django 6.0.3 on 2026-06-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_alter_gasto_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='hora',
            field=models.TimeField(help_text='Hora del gasto (automática)'),
        ),
    ]
