# Generated by Django 6.0.3 on 2026-06-23 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_alter_gasto_hora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('monto_inicial_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_final_efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('diferencia_efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas del turno')),
                ('abierto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_abiertos', to=settings.AUTH_USER_MODEL)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_cerrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno de caja',
                'verbose_name_plural': 'Turnos de caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
    ]
