# Generated by Django 6.0.3 on 2026-06-29 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_turnocaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='origen',
            field=models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('manual', 'Carga manual'), ('ajuste', 'Ajuste'), ('transaccion', 'Transacción interna')], default='manual', max_length=15),
        ),
        migrations.CreateModel(
            name='TransaccionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('deposito', 'Depósito bancario'), ('extraccion', 'Extracción bancaria'), ('compra_divisa', 'Compra de divisa'), ('venta_divisa', 'Venta de divisa')], max_length=20)),
                ('monto_origen', models.DecimalField(decimal_places=2, help_text='Monto que sale de cuenta_origen (en la moneda de esa cuenta).', max_digits=14)),
                ('monto_destino', models.DecimalField(decimal_places=2, help_text='Monto que entra en cuenta_destino (en la moneda de esa cuenta). Para depósito/extracción es igual a monto_origen. Para compra/venta de divisa es monto_origen / tipo_cambio.', max_digits=14)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=6, help_text='Precio de 1 unidad de la divisa destino en moneda origen. Ej: si comprás USD a 1.200 ARS, tipo_cambio=1200. Solo aplica para compra/venta de divisa.', max_digits=14, null=True)),
                ('costo_extra', models.DecimalField(blank=True, decimal_places=2, help_text='Monto adicional cobrado (impuesto, comisión, etc.), en la moneda de cuenta_origen.', max_digits=14, null=True)),
                ('descripcion_costo', models.CharField(blank=True, help_text='Descripción del costo extra. Ej: "Impuesto PAIS 30%", "Comisión bancaria".', max_length=200)),
                ('fecha', models.DateField(help_text='Fecha contable de la transacción.')),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_caja_creadas', to=settings.AUTH_USER_MODEL)),
                ('cuenta_destino', models.ForeignKey(help_text='Cuenta hacia la que entra el dinero.', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_como_destino', to='caja.cuentacaja')),
                ('cuenta_origen', models.ForeignKey(help_text='Cuenta desde la que sale el dinero.', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_como_origen', to='caja.cuentacaja')),
                ('mov_costo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_como_costo', to='caja.movimientocaja')),
                ('mov_egreso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_como_egreso', to='caja.movimientocaja')),
                ('mov_ingreso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_como_ingreso', to='caja.movimientocaja')),
            ],
            options={
                'verbose_name': 'Transacción de caja',
                'verbose_name_plural': 'Transacciones de caja',
                'ordering': ['-fecha', '-fecha_alta'],
            },
        ),
    ]
