# Generated by Django 6.0.3 on 2026-07-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_alter_movimientocaja_origen_transaccioncaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnocaja',
            name='totales_cierre',
            field=models.JSONField(blank=True, default=None, help_text='Snapshot de totales_medio_pago/total_recaudado/ganancia al cerrar el turno.', null=True),
        ),
    ]
