# Generated by Django 6.0.3 on 2026-07-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_turnocaja_totales_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacaja',
            name='dia_cierre',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Día del mes en que cierra el resumen (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='cuentacaja',
            name='dia_vencimiento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Día del mes en que vence el pago (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='cuentacaja',
            name='terminada_en',
            field=models.CharField(blank=True, help_text='Últimos 4 dígitos, alias o CBU corto. No guardar el número completo de tarjeta.', max_length=20),
        ),
        migrations.AddField(
            model_name='cuentacaja',
            name='titular',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='cuentacaja',
            name='tipo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta de crédito'), ('tarjeta_debito', 'Tarjeta de débito'), ('billetera_virtual', 'Billetera virtual'), ('cuenta_bancaria', 'Cuenta bancaria'), ('banco', 'Cuenta bancaria (legacy)'), ('otra', 'Otra (legacy)')], default='efectivo', max_length=20),
        ),
    ]
