# Generated by Django 6.0.3 on 2026-07-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0008_cuentacaja_dia_cierre_cuentacaja_dia_vencimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacaja',
            name='dia_cierre',
        ),
        migrations.RemoveField(
            model_name='cuentacaja',
            name='dia_vencimiento',
        ),
        migrations.RemoveField(
            model_name='cuentacaja',
            name='terminada_en',
        ),
        migrations.RemoveField(
            model_name='cuentacaja',
            name='titular',
        ),
        migrations.AlterField(
            model_name='cuentacaja',
            name='tipo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('banco', 'Cuenta bancaria'), ('otra', 'Otra')], default='efectivo', max_length=20),
        ),
    ]
