# Generated by Django 6.0.3 on 2026-07-10 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0009_remove_cuentacaja_dia_cierre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaFisicaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Caja 1', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas_fisicas', to='caja.turnocaja')),
            ],
            options={
                'verbose_name': 'Caja física de turno',
                'verbose_name_plural': 'Cajas físicas de turno',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
