# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0010_cajafisicaturno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacaja',
            name='titular',
            field=models.CharField(blank=True, help_text='Solo si difiere del titular del negocio.', max_length=150),
        ),
        migrations.AddField(
            model_name='cuentacaja',
            name='terminada_en',
            field=models.CharField(blank=True, help_text='Últimos 4 dígitos, alias o CBU corto. Nunca el número completo.', max_length=20),
        ),
        migrations.AddField(
            model_name='cuentacaja',
            name='es_credito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuentacaja',
            name='dia_cierre',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Día del mes en que cierra el resumen (1-31). Solo si es_credito.', null=True),
        ),
        migrations.AddField(
            model_name='cuentacaja',
            name='dia_vencimiento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Día del mes en que vence el pago (1-31). Solo si es_credito.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cuentacaja',
            unique_together={('nombre', 'caja', 'moneda')},
        ),
    ]
