# Generated by Django 6.0.3 on 2026-07-10 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0011_cuentacaja_es_credito_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'Ingreso o egreso manual', 'verbose_name_plural': 'Ingresos y egresos manuales'},
        ),
        migrations.AddField(
            model_name='gasto',
            name='cuenta',
            field=models.ForeignKey(default=1, help_text='Cuenta que se acredita o debita con este movimiento.', on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='caja.cuentacaja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='egreso', max_length=10),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(help_text='Ej: alquiler, mecánico, luz, sueldo, herencia, regalo', max_length=300),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(help_text='Fecha del movimiento'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='hora',
            field=models.TimeField(help_text='Hora del movimiento (automática)'),
        ),
    ]
