# Generated by Django 6.0.3 on 2026-07-12 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0012_alter_gasto_options_gasto_cuenta_gasto_tipo_and_more'),
        ('compras', '0012_alter_compra_medio_pago_alter_pagocompra_medio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='origen',
            field=models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('manual', 'Carga manual'), ('ajuste', 'Ajuste'), ('transaccion', 'Transacción interna'), ('deuda', 'Deuda (acreditación de préstamo)'), ('cuota_deuda', 'Cuota de deuda')], default='manual', max_length=15),
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra_credito', 'Compra con tarjeta de crédito'), ('prestamo', 'Préstamo')], max_length=20)),
                ('descripcion', models.CharField(blank=True, help_text='Obligatoria si no viene de una compra (ej: "Notebook oficina", "Préstamo Banco Nación").', max_length=300)),
                ('monto_original', models.DecimalField(decimal_places=2, help_text='Capital, sin interés.', max_digits=14)),
                ('porcentaje_interes', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('moneda', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=5)),
                ('cantidad_cuotas', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField(help_text='Vencimiento de la primera cuota. Las siguientes son mensuales a partir de acá.')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('anulada', 'Anulada')], default='activa', max_length=10)),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deudas_creadas', to=settings.AUTH_USER_MODEL)),
                ('cuenta_acreditacion', models.ForeignKey(blank=True, help_text='Cuenta que recibe el dinero del préstamo. Solo para prestamo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deudas_acreditadas', to='caja.cuentacaja')),
                ('cuenta_tarjeta', models.ForeignKey(blank=True, help_text='Tarjeta (CuentaCaja con es_credito=True) usada. Solo para compra_credito.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deudas_tarjeta', to='caja.cuentacaja')),
                ('pago_compra', models.OneToOneField(blank=True, help_text='Solo si esta deuda nació de una línea de pago con tarjeta en una compra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deuda', to='compras.pagocompra')),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='CuotaDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='pendiente', max_length=10)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_deuda_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('cuenta_pago', models.ForeignKey(blank=True, help_text='Cuenta real (banco/efectivo) de donde sale la plata al confirmar. Nunca una tarjeta.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuotas_pagadas', to='caja.cuentacaja')),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='caja.deuda')),
            ],
            options={
                'verbose_name': 'Cuota de deuda',
                'verbose_name_plural': 'Cuotas de deuda',
                'ordering': ['deuda', 'numero'],
                'unique_together': {('deuda', 'numero')},
            },
        ),
    ]
