# Generated by Django 6.0.3 on 2026-07-12 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0013_alter_movimientocaja_origen_deuda_cuotadeuda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='origen',
            field=models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('manual', 'Carga manual'), ('ajuste', 'Ajuste'), ('transaccion', 'Transacción interna'), ('deuda', 'Deuda (acreditación de préstamo)'), ('cuota_deuda', 'Cuota de deuda'), ('cheque', 'Cheque')], default='manual', max_length=15),
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('a_cobrar', 'A cobrar (de terceros)'), ('a_pagar', 'A pagar (propio)')], max_length=10)),
                ('numero_cheque', models.CharField(blank=True, help_text='Opcional, ayuda a evitar duplicados.', max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=5)),
                ('fecha_emision', models.DateField(help_text='Fecha en que se emitió/recibió el cheque.')),
                ('fecha_cobro', models.DateField(help_text='Fecha en que se puede/debe cobrar (cubre cheque común y de pago diferido).')),
                ('banco_librador', models.CharField(blank=True, help_text='Banco del cheque de terceros. Solo informativo.', max_length=100)),
                ('titular_librador', models.CharField(blank=True, help_text='Quién entregó el cheque. Solo para A_COBRAR.', max_length=150)),
                ('contraparte', models.CharField(blank=True, help_text='A quién se le paga (A_PAGAR) o quién lo entregó (A_COBRAR).', max_length=150)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('anulado', 'Anulado')], default='pendiente', max_length=10)),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_confirmados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_destino', models.ForeignKey(blank=True, help_text='Cuenta propia donde se deposita/cobra. Se completa al confirmar, no antes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques_a_cobrar', to='caja.cuentacaja')),
                ('cuenta_origen', models.ForeignKey(blank=True, help_text='Cuenta bancaria propia (la chequera). Solo para A_PAGAR.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheques_a_pagar', to='caja.cuentacaja')),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
                'ordering': ['-fecha_alta'],
            },
        ),
    ]
