# Generated by Django 6.0.3 on 2026-07-18 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0014_alter_movimientocaja_origen_cheque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='turnocaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierto')), fields=('estado',), name='unico_turno_abierto'),
        ),
    ]
