# Generated by Django 6.0.3 on 2026-07-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0015_turnocaja_unico_turno_abierto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccioncaja',
            name='tipo',
            field=models.CharField(choices=[('deposito', 'Depósito bancario'), ('extraccion', 'Extracción bancaria'), ('transferencia', 'Transferencia entre cuentas'), ('compra_divisa', 'Compra de divisa'), ('venta_divisa', 'Venta de divisa')], max_length=20),
        ),
    ]
