# Generated by Django 6.0.3 on 2026-07-20 17:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0016_alter_transaccioncaja_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotadeuda',
            name='monto_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Porción de `monto` que es capital (sin interés). El resto (monto - monto_capital) es interés. Solo relevante para compra_credito: es lo que se acredita a la tarjeta al confirmar, para que su saldo vuelva a acercarse a 0.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='origen',
            field=models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('manual', 'Carga manual'), ('ajuste', 'Ajuste'), ('transaccion', 'Transacción interna'), ('deuda', 'Deuda (acreditación de préstamo)'), ('cuota_deuda', 'Cuota de deuda'), ('cheque', 'Cheque'), ('deuda_tarjeta', 'Compra con tarjeta (débito en tarjeta)'), ('cuota_deuda_tarjeta', 'Pago de cuota (capital acreditado a tarjeta)')], default='manual', max_length=20),
        ),
    ]
