# Generated by Django 6.0.3 on 2026-07-26 18:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0017_cuotadeuda_monto_capital_alter_movimientocaja_origen'),
        ('core', '0023_alter_usuariopermisooverride_permiso'),
        ('ventas', '0016_alter_pagoventa_medio_alter_venta_medio_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='origen',
            field=models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('manual', 'Carga manual'), ('ajuste', 'Ajuste'), ('transaccion', 'Transacción interna'), ('deuda', 'Deuda (acreditación de préstamo)'), ('cuota_deuda', 'Cuota de deuda'), ('cheque', 'Cheque'), ('deuda_tarjeta', 'Compra con tarjeta (débito en tarjeta)'), ('cuota_deuda_tarjeta', 'Pago de cuota (capital acreditado a tarjeta)'), ('cuota_cobro', 'Cobro de cuota (venta en cuotas)')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('monto_original', models.DecimalField(decimal_places=2, help_text='Precio de venta, sin interés.', max_digits=14)),
                ('porcentaje_interes', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('moneda', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=5)),
                ('cantidad_cuotas', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField(help_text='Vencimiento de la primera cuota. Las siguientes son mensuales a partir de acá.')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('anulada', 'Anulada')], default='activa', max_length=10)),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='A quién hay que cobrarle. Obligatorio: no se puede vender en cuotas a Consumidor Final.', on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_cobrar', to='core.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_por_cobrar_creadas', to=settings.AUTH_USER_MODEL)),
                ('pago_venta', models.OneToOneField(blank=True, help_text='Línea de pago (medio=cuotas) de la venta que originó esta cuenta por cobrar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_por_cobrar', to='ventas.pagoventa')),
            ],
            options={
                'verbose_name': 'Cuenta por cobrar',
                'verbose_name_plural': 'Cuentas por cobrar',
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='CuotaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_capital', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Porción de `monto` que es capital (sin interés). El resto es interés — informativo, no cambia cuánto ingresa a caja al confirmar (eso es siempre `monto`).', max_digits=14)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='pendiente', max_length=10)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_cobro_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('cuenta_cobro', models.ForeignKey(blank=True, help_text='Cuenta real (banco/efectivo) a la que entra la plata al confirmar el cobro.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuotas_cobradas', to='caja.cuentacaja')),
                ('cuenta_por_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='caja.cuentaporcobrar')),
            ],
            options={
                'verbose_name': 'Cuota de cobro',
                'verbose_name_plural': 'Cuotas de cobro',
                'ordering': ['cuenta_por_cobrar', 'numero'],
                'unique_together': {('cuenta_por_cobrar', 'numero')},
            },
        ),
    ]
