# Generated by Django 6.0.3 on 2026-07-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0018_alter_movimientocaja_origen_cuentaporcobrar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacaja',
            name='acepta_credito',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuentacaja',
            name='acepta_debito',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuentacaja',
            name='acepta_qr',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cuentacaja',
            name='acepta_transferencia',
            field=models.BooleanField(default=True),
        ),
    ]
