# Generated by Django 6.0.3 on 2026-08-01 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0020_cheque_numero_factura_and_more'),
        ('ventas', '0024_alter_pagoventa_medio_alter_venta_medio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='pago_venta',
            field=models.ForeignKey(blank=True, help_text='Línea de pago (medio=cheque) de la venta que originó este cheque, si corresponde.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='ventas.pagoventa'),
        ),
    ]
