# Generated by Django 6.0.3 on 2026-08-01 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0021_cheque_pago_venta'),
        ('compras', '0017_alter_compra_medio_pago_alter_pagocompra_medio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='pago_compra',
            field=models.ForeignKey(blank=True, help_text='Línea de pago (medio=cheque) de la compra que originó este cheque, si corresponde.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='compras.pagocompra'),
        ),
    ]
