# Generated by Django 6.0.3 on 2026-08-01 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0022_cheque_pago_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='cuota_cobro',
            field=models.ForeignKey(blank=True, help_text='Cuota de cobro que este cheque saldó, si nació de "cobrar cuota con cheque".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='caja.cuotacobro'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='cuota_deuda',
            field=models.ForeignKey(blank=True, help_text='Cuota de deuda que este cheque pagó, si nació de "pagar cuota con cheque".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='caja.cuotadeuda'),
        ),
    ]
