# Generated by Django 6.0.3 on 2026-08-03 01:08

import caja.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0023_cheque_cuota_cobro_cheque_cuota_deuda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotadeuda',
            name='es_historica',
            field=models.BooleanField(default=False, help_text='Cuota que ya estaba pagada antes de cargar la deuda al sistema (carga inicial). No generó movimiento de caja real: no hay registro del ingreso que la bancó.'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='es_carga_inicial',
            field=models.BooleanField(default=False, help_text='Deuda que ya existía antes de empezar a usar el sistema. Las cuotas marcadas como ya pagadas al crearla (ver CuotaDeuda.es_historica) no generan movimiento de caja, y si es un préstamo tampoco se acredita el ingreso — esa plata ya entró/salió antes de tener registro acá.'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='numero_comprobante',
            field=models.CharField(blank=True, help_text='N° de factura/comprobante del proveedor o entidad, si corresponde.', max_length=100),
        ),
        migrations.CreateModel(
            name='DeudaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=caja.models._deuda_doc_path)),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('contrato', 'Contrato'), ('recibo', 'Recibo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('subido_el', models.DateTimeField(auto_now_add=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='caja.deuda')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de deuda',
                'verbose_name_plural': 'Documentos de deuda',
                'ordering': ['subido_el'],
            },
        ),
    ]
