# Generated by Django 6.0.3 on 2026-08-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0024_cuotadeuda_es_historica_deuda_es_carga_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='modo_cuotas',
            field=models.CharField(choices=[('fijas', 'Cuotas fijas'), ('libre', 'Cuotas libres')], default='fijas', help_text='Fijas: plan de N cuotas iguales con vencimiento mensual (como hoy). Libre: no hay plan — se van registrando abonos de cualquier monto (ver Deuda.registrar_abono) hasta cubrir el total.', max_length=10),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='cantidad_cuotas',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Solo aplica a modo_cuotas=fijas.', null=True),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='fecha_inicio',
            field=models.DateField(help_text='modo_cuotas=fijas: vencimiento de la primera cuota (las siguientes son mensuales a partir de acá). modo_cuotas=libre: fecha de origen de la deuda.'),
        ),
    ]
