# Generated by Django 6.0.3 on 2026-08-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0025_deuda_modo_cuotas_alter_deuda_cantidad_cuotas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotadeuda',
            name='medio_pago_historico',
            field=models.CharField(blank=True, help_text='Solo para cuotas es_historica: con qué se pagó (ej. "Efectivo", "Transferencia Galicia"), a modo de registro. No referencia una CuentaCaja real ni afecta ningún saldo — cuenta_pago se deja en None a propósito para esas cuotas (ver sincronizar_movimiento_cuota).', max_length=100),
        ),
    ]
