# Generated by Django 6.0.3 on 2026-08-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0026_cuotadeuda_medio_pago_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='es_historico',
            field=models.BooleanField(default=False, help_text='Cheque que ya se pagó/cobró antes de cargar la deuda al sistema (carga inicial de una CuotaDeuda es_historica). Se guarda CONFIRMADO de una, pero nunca genera movimiento de caja real — mismo criterio que CuotaDeuda.es_historica (ver sincronizar_movimiento_cheque).'),
        ),
        migrations.AddField(
            model_name='cuotadeuda',
            name='cuenta_pago_historica',
            field=models.ForeignKey(blank=True, help_text='Solo para cuotas es_historica: con qué cuenta real se pagó (ej. Efectivo, Mercado Pago), a modo de registro/trazabilidad. NUNCA genera movimiento ni afecta el saldo de esa cuenta — cuenta_pago se deja en None a propósito para esas cuotas (ver sincronizar_movimiento_cuota). Si el pago histórico fue con cheque, ver Cheque.es_historico en su lugar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuotas_pagadas_historicas', to='caja.cuentacaja'),
        ),
        migrations.AlterField(
            model_name='cuotadeuda',
            name='medio_pago_historico',
            field=models.CharField(blank=True, help_text='Solo para cuotas es_historica y solo cuando no aplica ni cuenta_pago_historica ni un Cheque.es_historico (ej. "permuta", "compensación con otra deuda") — nota libre de registro.', max_length=100),
        ),
    ]
