# Generated by Django 6.0.3 on 2026-08-03 19:43

import caja.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0027_cheque_es_historico_cuotadeuda_cuenta_pago_historica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='es_carga_inicial',
            field=models.BooleanField(default=False, help_text='Cuenta por cobrar que ya existía antes de empezar a usar el sistema. Las cuotas marcadas como ya cobradas al crearla (ver CuotaCobro.es_historica) no generan movimiento de caja — esa plata ya entró antes de tener registro acá.'),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='modo_cuotas',
            field=models.CharField(choices=[('fijas', 'Cuotas fijas'), ('libre', 'Cuotas libres')], default='fijas', help_text='Fijas: plan de N cuotas iguales con vencimiento mensual (como hoy). Libre: no hay plan — se van registrando abonos de cualquier monto (ver CuentaPorCobrar.registrar_abono) hasta cubrir el total.', max_length=10),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='numero_comprobante',
            field=models.CharField(blank=True, help_text='N° de factura/comprobante que se le dio al cliente, si corresponde.', max_length=100),
        ),
        migrations.AddField(
            model_name='cuotacobro',
            name='cuenta_pago_historica',
            field=models.ForeignKey(blank=True, help_text='Solo para cuotas es_historica: con qué cuenta real se cobró (ej. Efectivo, Mercado Pago), a modo de registro/trazabilidad. NUNCA genera movimiento ni afecta el saldo de esa cuenta — cuenta_cobro se deja en None a propósito para esas cuotas (ver sincronizar_movimiento_cuota_cobro). Si el pago histórico fue con cheque, ver Cheque.es_historico en su lugar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuotas_cobro_historicas', to='caja.cuentacaja'),
        ),
        migrations.AddField(
            model_name='cuotacobro',
            name='es_historica',
            field=models.BooleanField(default=False, help_text='Cuota que ya estaba cobrada antes de cargar la cuenta al sistema (carga inicial). No generó movimiento de caja real: no hay registro del ingreso que la originó.'),
        ),
        migrations.AddField(
            model_name='cuotacobro',
            name='medio_pago_historico',
            field=models.CharField(blank=True, help_text='Solo para cuotas es_historica y solo cuando no aplica ni cuenta_pago_historica ni un Cheque.es_historico (ej. "permuta", "compensación con otra deuda") — nota libre de registro.', max_length=100),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='cantidad_cuotas',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Solo aplica a modo_cuotas=fijas.', null=True),
        ),
        migrations.CreateModel(
            name='CuentaPorCobrarDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=caja.models._cuenta_cobrar_doc_path)),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('contrato', 'Contrato'), ('recibo', 'Recibo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('subido_el', models.DateTimeField(auto_now_add=True)),
                ('cuenta_por_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='caja.cuentaporcobrar')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de cuenta por cobrar',
                'verbose_name_plural': 'Documentos de cuenta por cobrar',
                'ordering': ['subido_el'],
            },
        ),
    ]
