# Generated by Django 6.0.3 on 2026-08-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0028_cuentaporcobrar_es_carga_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='tipo',
            field=models.CharField(choices=[('compra_credito', 'Compra con tarjeta de crédito'), ('prestamo', 'Préstamo'), ('cheque', 'Compra con cheque')], max_length=20),
        ),
    ]
