# Generated by Django 6.0.3 on 2026-08-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0029_alter_deuda_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='origen',
            field=models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('manual', 'Carga manual'), ('ajuste', 'Ajuste'), ('transaccion', 'Transacción interna'), ('deuda', 'Deuda (acreditación de préstamo)'), ('cuota_deuda', 'Cuota de deuda'), ('cheque', 'Cheque'), ('deuda_tarjeta', 'Compra con tarjeta (débito en tarjeta)'), ('cuota_deuda_tarjeta', 'Pago de cuota (capital acreditado a tarjeta)'), ('cuota_cobro', 'Cobro de cuota (venta en cuotas)'), ('devolucion_venta', 'Devolución de venta')], default='manual', max_length=20),
        ),
    ]
