# Generated by Django 6.0.3 on 2026-08-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0030_alter_movimientocaja_origen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuentacaja',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cuentacaja',
            name='titular',
            field=models.CharField(blank=True, help_text='Nombre de quien es titular de la tarjeta/cuenta. Obligatorio salvo para Efectivo.', max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='cuentacaja',
            unique_together={('nombre', 'caja', 'moneda', 'titular', 'es_credito')},
        ),
    ]
