# Generated by Django 6.0.3 on 2026-08-27 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0031_alter_cuentacaja_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('descripcion', models.CharField(help_text='Ej: "Alquiler local", "Sueldo Juan Pérez", "Cuenta de luz".', max_length=300)),
                ('moneda', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=5)),
                ('tipo_monto', models.CharField(choices=[('fijo', 'Monto fijo (igual cada vez)'), ('variable', 'Monto variable (se carga cada vez)')], max_length=10)),
                ('monto_fijo', models.DecimalField(blank=True, decimal_places=2, help_text='Solo si tipo_monto=fijo — se precarga en cada instancia (editable al confirmar).', max_digits=14, null=True)),
                ('frecuencia', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('anual', 'Anual')], max_length=10)),
                ('proxima_fecha', models.DateField(help_text='Próxima fecha en la que se genera la siguiente instancia pendiente.')),
                ('activo', models.BooleanField(default=True, help_text='Si se pausa, no genera más instancias nuevas — las ya generadas se pueden seguir confirmando o anulando igual.')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programados_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(help_text='Cuenta sugerida al confirmar cada instancia (se puede cambiar en el momento).', on_delete=django.db.models.deletion.PROTECT, related_name='programados', to='caja.cuentacaja')),
            ],
            options={
                'verbose_name': 'Movimiento programado',
                'verbose_name_plural': 'Movimientos programados',
                'ordering': ['proxima_fecha'],
            },
        ),
        migrations.CreateModel(
            name='InstanciaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='pendiente', max_length=10)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, help_text='Precargado si el programado es de monto fijo; vacío si es variable hasta que se completa al confirmar.', max_digits=14, null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias_programadas_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('gasto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancia_programada', to='caja.gasto')),
                ('programado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='caja.movimientoprogramado')),
            ],
            options={
                'verbose_name': 'Instancia programada',
                'verbose_name_plural': 'Instancias programadas',
                'ordering': ['fecha_vencimiento'],
                'unique_together': {('programado', 'fecha_vencimiento')},
            },
        ),
    ]
