# Generated by Django 6.0.3 on 2026-08-31 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0032_movimientoprogramado_instanciaprogramada'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPredeterminadaMedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito'), ('qr', 'QR'), ('transferencia', 'Transferencia')], max_length=20, unique=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='caja.cuentacaja')),
            ],
            options={
                'verbose_name': 'Cuenta predeterminada por medio de pago',
                'verbose_name_plural': 'Cuentas predeterminadas por medio de pago',
                'ordering': ['medio'],
            },
        ),
    ]
