# Generated by Django 6.0.3 on 2026-08-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0033_cuentapredeterminadamedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacaja',
            name='preferida',
            field=models.BooleanField(default=False, verbose_name='Cuenta principal'),
        ),
    ]
