# Generated by Django 6.0.3 on 2026-09-03 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0034_cuentacaja_preferida'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='turno',
            field=models.ForeignKey(blank=True, help_text='Si viene de la pantalla de Caja Diaria: el turno cuyo cajón afecta.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_manuales', to='caja.turnocaja'),
        ),
    ]
