# Generated by Django 6.0.3 on 2026-09-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0035_gasto_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoprogramado',
            name='frecuencia',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('anual', 'Anual')], max_length=10),
        ),
    ]
