# Generated by Django 6.0.3 on 2026-09-03 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0036_alter_movimientoprogramado_frecuencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_normalizado', models.CharField(editable=False, max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], default='egreso', help_text='Si suele ser ingreso o egreso — ordena las sugerencias.', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Concepto de ingreso/egreso',
                'verbose_name_plural': 'Conceptos de ingresos/egresos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='concepto',
            field=models.ForeignKey(blank=True, help_text='Concepto del catálogo — se resuelve solo desde la descripción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='caja.conceptogasto'),
        ),
    ]
