# Generated by Django 6.0.3 on 2026-09-04 21:19

import caja.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0039_backfill_ganancia_bruta_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='foto_pagare',
            field=models.ImageField(blank=True, help_text='Foto del pagaré ya firmado, por si se pierde el papel.', null=True, upload_to=caja.models._cuenta_cobrar_pagare_path),
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='numero_pagare',
            field=models.CharField(blank=True, help_text='N° del pagaré firmado por el cliente como respaldo legal, si corresponde.', max_length=100),
        ),
        migrations.AddField(
            model_name='cuotacobro',
            name='numero_comprobante',
            field=models.CharField(blank=True, help_text='N° del comprobante/recibo entregado al cliente al cobrar esta cuota, si corresponde.', max_length=100),
        ),
    ]
