# Generated by Django 6.0.3 on 2026-09-08 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0040_cuentaporcobrar_foto_pagare_and_more'),
        ('core', '0038_configuracionventas_modo_cobranza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CobroCuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, help_text='Total cobrado e imputado a las deudas del cliente.', max_digits=14)),
                ('moneda', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], default='ARS', max_length=5)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100)),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('anulado', 'Anulado')], default='activo', max_length=10)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros_cuenta_corriente', to='core.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros_cuenta_corriente_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(help_text='Cuenta real (efectivo/banco) a la que entró la plata.', on_delete=django.db.models.deletion.PROTECT, related_name='cobros_cuenta_corriente', to='caja.cuentacaja')),
            ],
            options={
                'verbose_name': 'Cobro por cuenta corriente',
                'verbose_name_plural': 'Cobros por cuenta corriente',
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.AddField(
            model_name='cuotacobro',
            name='cobro_cuenta_corriente',
            field=models.ForeignKey(blank=True, help_text='Si esta cuota/abono lo generó un cobro contra el saldo total del cliente (modo cuenta corriente), acá está ese recibo. Anular el recibo revierte esta imputación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_imputadas', to='caja.cobrocuentacorriente'),
        ),
    ]
