# Generated by Django 6.0.3 on 2026-09-08 03:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0041_cobrocuentacorriente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrocuentacorriente',
            name='saldo_posterior',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Saldo total del cliente inmediatamente después de este cobro — snapshot para el recibo (no se recalcula).', max_digits=14),
        ),
    ]
