# Generated by Django 6.0.3 on 2026-09-08 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0042_cobrocuentacorriente_saldo_posterior'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turnocaja',
            name='veces_reabierto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReaperturaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='1 = primera vez que se reabrió este turno, 2 = segunda, etc.')),
                ('fecha_reapertura', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(help_text='Por qué se reabrió (obligatorio).')),
                ('efectivo_revertido', models.DecimalField(decimal_places=2, default=0, help_text='Efectivo que este turno había depositado en caja grande y que la reapertura sacó (se vuelve a depositar al re-cerrar).', max_digits=14)),
                ('era_ultimo_turno', models.BooleanField(default=True, help_text='Si al reabrirlo era el último turno (su ventana horaria pudo avanzar) o uno viejo (ventana congelada).')),
                ('snapshot_previo', models.JSONField(default=dict, help_text='Foto del cierre que se deshizo: totales, arqueo, diferencia, cajas.')),
                ('fecha_recierre', models.DateTimeField(blank=True, null=True)),
                ('diferencia_al_recerrar', models.DecimalField(blank=True, decimal_places=2, help_text='Diferencia de efectivo del turno tras el re-cierre.', max_digits=14, null=True)),
                ('reabierto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_reabiertos', to=settings.AUTH_USER_MODEL)),
                ('recerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_recerrados', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaperturas', to='caja.turnocaja')),
            ],
            options={
                'verbose_name': 'Reapertura de turno',
                'verbose_name_plural': 'Reaperturas de turno',
                'ordering': ['-fecha_reapertura'],
            },
        ),
    ]
