# Generated by Django 6.0.3 on 2026-09-10 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0043_turnocaja_veces_reabierto_reaperturaturno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(blank=True, help_text='Categoría libre (mueble, vehículo, terreno…). Se puede escribir cualquiera o dejarla vacía.', max_length=60)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional — valor estimado actual.', max_digits=14, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Notas libres: ubicación, estado, marca/modelo, lo que haga falta.')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar si se vendió o se dio de baja, sin perder el registro histórico.')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienes_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienes_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Bienes',
                'ordering': ['-activo', 'nombre'],
            },
        ),
    ]
