# Generated by Django 6.0.3 on 2026-09-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0044_bien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='modo_cuotas',
            field=models.CharField(choices=[('fijas', 'Cuotas fijas'), ('libre', 'Cuotas libres'), ('variable', 'Cuotas variables')], default='fijas', help_text='Fijas: plan de N cuotas iguales con vencimiento mensual (como hoy). Libre: no hay plan — se van registrando abonos de cualquier monto (ver CuentaPorCobrar.registrar_abono) hasta cubrir el total.', max_length=10),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='cantidad_cuotas',
            field=models.PositiveSmallIntegerField(blank=True, help_text='modo_cuotas=fijas: cantidad de cuotas iguales a generar. modo_cuotas=variable: plan total de referencia (ej. 72), opcional — no genera cuotas, solo sirve para mostrar "cuota 18 de 72" y para saber si el plan está completo al calcular el interés.', null=True),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='fecha_inicio',
            field=models.DateField(help_text='modo_cuotas=fijas: vencimiento de la primera cuota (las siguientes son mensuales a partir de acá). modo_cuotas=libre: fecha de origen de la deuda. modo_cuotas=variable: fecha de la cuota más temprana cargada (o el alta).'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='modo_cuotas',
            field=models.CharField(choices=[('fijas', 'Cuotas fijas'), ('libre', 'Cuotas libres'), ('variable', 'Cuotas variables')], default='fijas', help_text='Fijas: plan de N cuotas iguales con vencimiento mensual (como hoy). Libre: no hay plan — se van registrando abonos de cualquier monto (ver Deuda.registrar_abono) hasta cubrir el total. Variable: cuotas de monto distinto que se van cargando a mano, cada una con su fecha y monto (ver Deuda.editar_cuotas_pendientes) — el interés se calcula, el capital es opcional.', max_length=10),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='monto_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capital, sin interés. Puede quedar vacío en modo_cuotas=variable cuando no se conoce cuánto se pidió (ahí no se puede calcular el interés).', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='porcentaje_interes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='modo_cuotas=fijas/libre: lo tipea quien carga la deuda. modo_cuotas=variable: se calcula solo (ver Deuda.interes_implicito) — acá se guarda ese valor, o 0 si todavía no es calculable.', max_digits=6),
        ),
    ]
