# Generated by Django 6.0.3 on 2026-09-10 23:24

import django.db.models.deletion
from django.db import migrations, models


def backfill_pagos_cuota(apps, schema_editor):
    """
    Por cada CuotaDeuda ya CONFIRMADA con `cuenta_pago` seteado (pago de
    una sola cuenta, el único caso posible hasta ahora), crear 1
    PagoCuotaDeuda y re-apuntar su MovimientoCaja (origen=cuota_deuda) de
    origen_id=cuota.pk a origen_id=pago.pk (el nuevo esquema es por línea
    de pago).
    """
    CuotaDeuda = apps.get_model('caja', 'CuotaDeuda')
    PagoCuotaDeuda = apps.get_model('caja', 'PagoCuotaDeuda')
    MovimientoCaja = apps.get_model('caja', 'MovimientoCaja')

    for cuota in CuotaDeuda.objects.filter(estado='confirmada', cuenta_pago__isnull=False).iterator():
        pago = PagoCuotaDeuda.objects.create(
            cuota_id=cuota.pk, cuenta_id=cuota.cuenta_pago_id, monto=cuota.monto,
        )
        MovimientoCaja.objects.filter(
            origen='cuota_deuda', origen_app='caja', origen_id=cuota.pk,
        ).update(origen_id=pago.pk)


def revertir_backfill(apps, schema_editor):
    PagoCuotaDeuda = apps.get_model('caja', 'PagoCuotaDeuda')
    MovimientoCaja = apps.get_model('caja', 'MovimientoCaja')
    for pago in PagoCuotaDeuda.objects.select_related('cuota').iterator():
        MovimientoCaja.objects.filter(
            origen='cuota_deuda', origen_app='caja', origen_id=pago.pk,
        ).update(origen_id=pago.cuota_id)
    PagoCuotaDeuda.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0045_deuda_cuotas_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='tipo',
            field=models.CharField(choices=[('compra_credito', 'Compra con tarjeta de crédito'), ('prestamo', 'Préstamo'), ('cheque', 'Compra con cheque'), ('otro', 'Otra deuda')], max_length=20),
        ),
        migrations.CreateModel(
            name='PagoCuotaDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(help_text='Cuenta real (banco/efectivo) de donde sale la plata. Nunca una tarjeta.', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_cuota_deuda', to='caja.cuentacaja')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='caja.cuotadeuda')),
            ],
            options={
                'verbose_name': 'Pago de cuota de deuda',
                'verbose_name_plural': 'Pagos de cuota de deuda',
                'ordering': ['cuota', 'pk'],
            },
        ),
        migrations.RunPython(backfill_pagos_cuota, revertir_backfill),
    ]
