# Generated by Django 6.0.3 on 2026-09-12 03:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0046_deuda_pago_dividido_y_tipo_otro'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='descuento_acreditacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Solo prestamo: sellado, seguro u otros importes que el banco descuenta antes de depositar. No afecta el capital de la deuda (`monto_original`) ni el cálculo de interés/cuotas, que siguen siendo sobre el monto pedido completo — solo se resta al acreditar (ver `monto_acreditado` y sincronizar_movimiento_deuda). En una deuda de carga inicial no tiene efecto: esa plata ya entró antes de tener registro acá.', max_digits=14),
        ),
    ]
