# Generated by Django 6.0.3 on 2026-09-13 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0047_deuda_descuento_acreditacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('titular', models.CharField(blank=True, help_text='Para qué/quién se usa esta línea (ej: "Vendedor", "Depósito").', max_length=120)),
                ('compania', models.CharField(blank=True, help_text='Movistar, Personal, Claro, etc.', max_length=60)),
                ('pin', models.CharField(blank=True, max_length=20, verbose_name='PIN')),
                ('puk', models.CharField(blank=True, max_length=20, verbose_name='PUK')),
                ('fecha_activacion', models.DateField(blank=True, null=True)),
                ('frecuencia_recarga_dias', models.PositiveIntegerField(blank=True, help_text='Cada cuántos días recordar recargar crédito. Vacío = sin recordatorio.', null=True)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celulares_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celulares_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Celular',
                'verbose_name_plural': 'Celulares',
                'ordering': ['-activo', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='RecargaCelular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('celular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='caja.celular')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recargas_celular_creadas', to=settings.AUTH_USER_MODEL)),
                ('gasto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recarga_celular', to='caja.gasto')),
            ],
            options={
                'verbose_name': 'Recarga de celular',
                'verbose_name_plural': 'Recargas de celular',
                'ordering': ['-fecha', '-fecha_alta'],
            },
        ),
    ]
