# Generated by Django 6.0.3 on 2026-09-13 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0048_celular_recargacelular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recargacelular',
            name='gasto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recarga_celular', to='caja.gasto'),
        ),
    ]
