# Generated by Django 6.0.3 on 2026-09-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0049_alter_recargacelular_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='iccid',
            field=models.CharField(blank=True, help_text='Número largo escrito en el chip (SIM) físico.', max_length=25, verbose_name='ICCID'),
        ),
        migrations.AddField(
            model_name='celular',
            name='imei',
            field=models.CharField(blank=True, help_text='Número de serie del teléfono (marcando *#06# se ve en pantalla).', max_length=20, verbose_name='IMEI'),
        ),
    ]
