# Generated by Django 6.0.3 on 2026-09-20 20:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0050_celular_iccid_celular_imei'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(help_text='1-12')),
                ('monto_ajuste', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cargo propio del resumen que NO viene de ninguna compra financiada: interés que cobra el banco, IVA, seguro, mantenimiento, etc. Puede ser negativo (una bonificación).', max_digits=14)),
                ('descripcion_ajuste', models.CharField(blank=True, max_length=200)),
                ('ajuste_pagado', models.BooleanField(default=False)),
                ('fecha_pago_ajuste', models.DateTimeField(blank=True, null=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cuenta_pago_ajuste', models.ForeignKey(blank=True, help_text='De dónde salió monto_ajuste al pagar el resumen.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='caja.cuentacaja')),
                ('cuenta_tarjeta', models.ForeignKey(help_text='Tarjeta (CuentaCaja con es_credito=True) que agrupa este resumen.', on_delete=django.db.models.deletion.PROTECT, related_name='resumenes', to='caja.cuentacaja')),
            ],
            options={
                'verbose_name': 'Resumen de tarjeta',
                'verbose_name_plural': 'Resúmenes de tarjeta',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('cuenta_tarjeta', 'anio', 'mes')},
            },
        ),
    ]
