# Generated by Django 6.0.3 on 2026-09-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0051_resumentarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='monto_desconocido',
            field=models.BooleanField(default=False, help_text='Solo modo_cuotas=libre, tipo prestamo/otro: todavía no se conoce el total a devolver ni la tasa de interés real — recién se van a saber cuando termine de pagarse (préstamos informales, sin cronograma del prestamista). Mientras esté prendido, `monto_total`/`saldo_pendiente` no se pueden calcular (dan None) y `registrar_abono` no tiene techo. Se apaga con `cerrar_monto_desconocido`, que fija el total real = lo abonado hasta ese momento y calcula desde ahí la tasa implícita — no se edita a mano.'),
        ),
    ]
