# Generated by Django 6.0.3 on 2026-09-22 16:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0052_deuda_monto_desconocido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotadeuda',
            name='cuenta_pago_extra',
            field=models.ForeignKey(blank=True, help_text='De dónde sale monto_extra. Se materializa recién cuando la cuota queda CONFIRMADA de verdad — si se pagó con cheque, eso pasa cuando el cheque se cobra (ver sincronizar_movimiento_cuota_extra), no cuando se emitió.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='caja.cuentacaja'),
        ),
        migrations.AddField(
            model_name='cuotadeuda',
            name='descripcion_extra',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cuotadeuda',
            name='monto_extra',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='Cargo extra cobrado al pagar esta cuota, aparte de su monto (ej: interés por mora, recargo del banco por pagar tarde). NO es parte de la deuda ni de su saldo/plan — es un movimiento de caja propio, igual que ResumenTarjeta.monto_ajuste. No aplica a cuotas es_historica (no generan movimiento real de ningún tipo).', max_digits=14),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='origen',
            field=models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('manual', 'Carga manual'), ('ajuste', 'Ajuste'), ('transaccion', 'Transacción interna'), ('deuda', 'Deuda (acreditación de préstamo)'), ('cuota_deuda', 'Cuota de deuda'), ('cuota_deuda_extra', 'Cargo extra de cuota de deuda'), ('cheque', 'Cheque'), ('deuda_tarjeta', 'Compra con tarjeta (débito en tarjeta)'), ('cuota_deuda_tarjeta', 'Pago de cuota (capital acreditado a tarjeta)'), ('cuota_cobro', 'Cobro de cuota (venta en cuotas)'), ('devolucion_venta', 'Devolución de venta')], default='manual', max_length=20),
        ),
    ]
