# Generated by Django 6.0.3 on 2026-05-28 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('productos', '0003_movimientostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='producto_codigo',
            field=models.CharField(blank=True, help_text='Snapshot del código del producto al momento de la compra.', max_length=50),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='producto_nombre',
            field=models.CharField(blank=True, help_text='Snapshot del nombre del producto al momento de la compra.', max_length=255),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='proveedor_nombre',
            field=models.CharField(blank=True, help_text='Snapshot del nombre del proveedor al momento de la compra.', max_length=200),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_compra', to='productos.producto'),
        ),
    ]
