# Generated by Django 6.0.3 on 2026-05-30 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_itemcompra_producto_codigo_and_more'),
        ('productos', '0004_producto_color_unico_producto_tiene_variantes_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_compra', to='productos.productocolor', verbose_name='Color / variante'),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='color_nombre',
            field=models.CharField(blank=True, help_text='Snapshot del nombre del color al momento de la compra.', max_length=50),
        ),
    ]
