# Generated by Django 6.0.3 on 2026-05-31 18:43

import compras.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_itemcompra_color_itemcompra_color_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=compras.models._compra_doc_path)),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('remito', 'Remito'), ('recibo', 'Recibo'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('subido_el', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='compras.compra')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de compra',
                'verbose_name_plural': 'Documentos de compra',
                'ordering': ['subido_el'],
            },
        ),
    ]
