# Generated by Django 6.0.3 on 2026-06-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_compradocumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcompra',
            name='color',
        ),
        migrations.RemoveField(
            model_name='itemcompra',
            name='color_nombre',
        ),
    ]
