# Generated by Django 6.0.3 on 2026-06-28 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_itemcompra_color_and_more'),
        ('productos', '0006_opcionvariante_variante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='combinacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_compra', to='productos.combinacionvariante', verbose_name='Combinación de variantes'),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='combinacion_descripcion',
            field=models.CharField(blank=True, help_text='Snapshot de la descripción de la combinación al momento de la compra.', max_length=300),
        ),
    ]
