# Generated by Django 6.0.3 on 2026-07-01 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_itemcompra_combinacion_and_more'),
        ('productos', '0009_alter_combinacionvariante_descripcion_combinacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Requerido para productos perecederos.', null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.CreateModel(
            name='LoteCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Se genera automáticamente: LT-2025-00001', max_length=20, unique=True)),
                ('cantidad_inicial', models.PositiveIntegerField(help_text='Cantidad de productos en este lote al momento de la compra.', verbose_name='Cantidad inicial')),
                ('cantidad_actual', models.PositiveIntegerField(help_text='Cantidad disponible actualmente en este lote.', verbose_name='Cantidad actual')),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Costo unitario de este lote (para cálculo de ganancias).', max_digits=12, verbose_name='Costo unitario')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento del lote (requerido para productos perecederos).', null=True, verbose_name='Fecha de vencimiento')),
                ('fecha_compra', models.DateField(help_text='Fecha en que se realizó la compra de este lote.', verbose_name='Fecha de compra')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar para preservar trazabilidad.')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('combinacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='productos.combinacionvariante', verbose_name='Combinación de variante')),
                ('item_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='compras.itemcompra', verbose_name='Ítem de compra')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Lote de compra',
                'verbose_name_plural': 'Lotes de compra',
                'ordering': ['-fecha_compra', '-fecha_alta'],
            },
        ),
    ]
