# Generated by Django 6.0.3 on 2026-07-11 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0012_alter_gasto_options_gasto_cuenta_gasto_tipo_and_more'),
        ('compras', '0007_itemcompra_fecha_vencimiento_lotecompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('qr', 'QR')], default='efectivo', max_length=20, verbose_name='Medio de pago'),
        ),
        migrations.CreateModel(
            name='PagoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('qr', 'QR')], default='efectivo', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='compras.compra')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_compra', to='caja.cuentacaja')),
            ],
            options={
                'verbose_name': 'Pago de compra',
                'verbose_name_plural': 'Pagos de compra',
                'ordering': ['id'],
            },
        ),
    ]
