# Generated by Django 6.0.3 on 2026-07-11 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_compra_medio_pago_pagocompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecompra',
            name='item_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='compras.itemcompra', verbose_name='Ítem de compra'),
        ),
    ]
