# Generated by Django 6.0.3 on 2026-07-11 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_lotecompra_item_compra'),
        ('productos', '0009_alter_combinacionvariante_descripcion_combinacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perdida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_codigo_snapshot', models.CharField(blank=True, max_length=20)),
                ('producto_nombre_snapshot', models.CharField(blank=True, max_length=255)),
                ('combinacion_desc_snapshot', models.CharField(blank=True, max_length=300)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motivo', models.CharField(choices=[('vencimiento', 'Vencimiento'), ('rotura', 'Rotura / daño'), ('otro', 'Otro')], max_length=20)),
                ('motivo_detalle', models.CharField(blank=True, max_length=300)),
                ('automatica', models.BooleanField(default=False, help_text='True si la generó el sistema al vencer el lote; False si se registró a mano.')),
                ('fecha', models.DateField(help_text='Fecha en que se detectó/registró la pérdida.')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('combinacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perdidas', to='productos.combinacionvariante')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perdidas', to='compras.lotecompra')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perdidas', to='productos.producto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perdidas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pérdida',
                'verbose_name_plural': 'Pérdidas',
                'ordering': ['-fecha', '-fecha_alta'],
            },
        ),
    ]
