# Generated by Django 6.0.3 on 2026-07-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_itemcompra_lista_descuento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('qr', 'QR'), ('credito', 'Crédito (tarjeta)')], default='efectivo', max_length=20, verbose_name='Medio de pago'),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='medio',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('qr', 'QR'), ('credito', 'Crédito (tarjeta)')], default='efectivo', max_length=20),
        ),
    ]
