# Generated by Django 6.0.3 on 2026-07-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_alter_compra_medio_pago_alter_pagocompra_medio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecompra',
            name='cantidad_actual',
            field=models.DecimalField(decimal_places=3, help_text='Cantidad disponible actualmente en este lote.', max_digits=12, verbose_name='Cantidad actual'),
        ),
        migrations.AlterField(
            model_name='lotecompra',
            name='cantidad_inicial',
            field=models.DecimalField(decimal_places=3, help_text='Cantidad de productos en este lote al momento de la compra.', max_digits=12, verbose_name='Cantidad inicial'),
        ),
        migrations.AlterField(
            model_name='perdida',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
