# Generated by Django 6.0.3 on 2026-07-14 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_alter_lotecompra_cantidad_actual_and_more'),
        ('productos', '0013_alter_movimientostock_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraccionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_origen_nombre_snapshot', models.CharField(blank=True, max_length=255)),
                ('producto_destino_nombre_snapshot', models.CharField(blank=True, max_length=255)),
                ('factor_conversion', models.DecimalField(decimal_places=3, help_text='Cuánto de producto_origen tiene una unidad de producto_destino.', max_digits=12)),
                ('cantidad_paquetes', models.DecimalField(decimal_places=3, help_text='Cuántas unidades de producto_destino se armaron.', max_digits=12)),
                ('cantidad_total_origen', models.DecimalField(decimal_places=3, help_text='factor_conversion × cantidad_paquetes — lo que se descontó de producto_origen.', max_digits=12)),
                ('costo_unitario_calculado', models.DecimalField(decimal_places=2, help_text='Costo de cada unidad de producto_destino, calculado desde el costo real de origen consumido.', max_digits=12)),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('fecha', models.DateField(help_text='Fecha en que se armaron los paquetes.')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraccionamientos_creados', to=settings.AUTH_USER_MODEL)),
                ('lote_destino', models.ForeignKey(blank=True, help_text='Lote creado para producto_destino con este fraccionamiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraccionamiento_de_origen', to='compras.lotecompra')),
                ('producto_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraccionamientos_como_destino', to='productos.producto')),
                ('producto_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraccionamientos_como_origen', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Fraccionamiento',
                'verbose_name_plural': 'Fraccionamientos',
                'ordering': ['-fecha', '-fecha_alta'],
            },
        ),
    ]
