# Generated by Django 6.0.3 on 2026-07-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_fraccionamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraccionamiento',
            name='cantidad_total_origen',
            field=models.DecimalField(decimal_places=3, help_text='Cuánto de producto_origen se usó para armar los paquetes.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='fraccionamiento',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=3, help_text='Cuánto de producto_origen equivale a una unidad de producto_destino (calculado).', max_digits=12),
        ),
    ]
