# Generated by Django 6.0.3 on 2026-07-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0015_alter_fraccionamiento_cantidad_total_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocompra',
            name='cotizacion',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Pesos por unidad de la moneda de la cuenta. Solo aplica si la cuenta no es en pesos.', max_digits=12, null=True, verbose_name='Cotización'),
        ),
    ]
