# Generated by Django 6.0.3 on 2026-08-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0017_alter_compra_medio_pago_alter_pagocompra_medio'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=100, verbose_name='N° de comprobante'),
        ),
    ]
