# Generated by Django 6.0.3 on 2026-08-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_compra_numero_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdida',
            name='precio_venta_unitario_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de venta del producto al momento de la pérdida — para saber no solo lo que costó, sino lo que se dejó de facturar por venderlo.', max_digits=12),
        ),
    ]
