# Generated by Django 6.0.3 on 2026-08-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0019_perdida_precio_venta_unitario_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='alicuota_iva',
            field=models.CharField(blank=True, choices=[('0', 'Exento (0%)'), ('10.5', 'Reducido (10,5%)'), ('21', 'General (21%)'), ('27', 'Especial (27%)')], help_text='Alícuota discriminada en la Factura del proveedor.', max_length=5, verbose_name='Alícuota IVA'),
        ),
        migrations.AddField(
            model_name='compra',
            name='iva_incluido',
            field=models.BooleanField(default=True, help_text='Si lo destildás, lo cargado en cada ítem es el costo SIN IVA (como el neto de una Factura A) y el sistema le suma el IVA de la alícuota elegida para calcular el total real a pagar.', verbose_name='El total ya incluye IVA'),
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('factura', 'Factura'), ('presupuesto', 'Presupuesto'), ('remito', 'Remito')], default='factura', max_length=20, verbose_name='Tipo de documento'),
        ),
    ]
