# Generated by Django 6.0.3 on 2026-08-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0021_desactivar_lotes_huerfanos'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='es_carga_inicial',
            field=models.BooleanField(default=False, verbose_name='Carga inicial de stock'),
        ),
        migrations.AddField(
            model_name='compra',
            name='factura_inicial_datos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
