# Generated by Django 6.0.3 on 2026-09-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0022_compra_es_carga_inicial_compra_factura_inicial_datos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('qr', 'QR'), ('credito', 'Crédito (tarjeta)'), ('cheque', 'Cheque'), ('cuenta_corriente', 'A pagar después (cuenta corriente)')], default='efectivo', max_length=20, verbose_name='Medio de pago'),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='medio',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('qr', 'QR'), ('credito', 'Crédito (tarjeta)'), ('cheque', 'Cheque'), ('cuenta_corriente', 'A pagar después (cuenta corriente)')], default='efectivo', max_length=20),
        ),
    ]
