# Generated by Django 6.0.3 on 2026-09-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0023_alter_compra_medio_pago_alter_pagocompra_medio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraccionamiento',
            name='costo_unitario_calculado',
            field=models.DecimalField(decimal_places=4, help_text='Costo de cada unidad de producto_destino, calculado desde el costo real de origen consumido.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Costo unitario'),
        ),
        migrations.AlterField(
            model_name='lotecompra',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=4, help_text='Costo unitario de este lote (para cálculo de ganancias).', max_digits=14, verbose_name='Costo unitario'),
        ),
        migrations.AlterField(
            model_name='perdida',
            name='costo_unitario_snapshot',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='perdida',
            name='precio_venta_unitario_snapshot',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Precio de venta del producto al momento de la pérdida — para saber no solo lo que costó, sino lo que se dejó de facturar por venderlo.', max_digits=14),
        ),
    ]
