# Generated by Django 6.0.3 on 2026-09-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0024_alter_fraccionamiento_costo_unitario_calculado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdida',
            name='cantidad_recuperada',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Unidades de esta pérdida por vencimiento que después se vendieron igual (ver recuperar_perdidas_vencimiento). `cantidad` ya es lo que quedó perdido de verdad: se le restan.', max_digits=12),
        ),
    ]
